/*
Navicat MySQL Data Transfer

Source Server         : 8isp
Source Server Version : 50519
Source Host           : 27.54.195.78:3306
Source Database       : sq652874007

Target Server Type    : MYSQL
Target Server Version : 50519
File Encoding         : 65001

Date: 2012-08-05 19:52:59
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `picname`
-- ----------------------------
DROP TABLE IF EXISTS `picname`;
CREATE TABLE `picname` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=256 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of picname
-- ----------------------------
INSERT INTO `picname` VALUES ('1', '000000.gif');
INSERT INTO `picname` VALUES ('2', '0_7fb27_2e66fae6_XL.jpg');
INSERT INTO `picname` VALUES ('3', '0_7fb28_748c73be_XL.jpg');
INSERT INTO `picname` VALUES ('4', '0_7fb29_d869c1da_XL.jpg');
INSERT INTO `picname` VALUES ('5', '0_7fb2a_869c3fdb_XL.jpg');
INSERT INTO `picname` VALUES ('6', '0_7fb2b_4880f26_XL.jpg');
INSERT INTO `picname` VALUES ('7', '0_7fb2c_189dbc71_XL.jpg');
INSERT INTO `picname` VALUES ('8', '0_7fb2d_df3afaff_XL.jpg');
INSERT INTO `picname` VALUES ('9', '0_7fb2e_23ea11d1_XL.jpg');
INSERT INTO `picname` VALUES ('10', '0_7fb2f_6c2cd930_XL.jpg');
INSERT INTO `picname` VALUES ('11', '0_7fb30_e9d3d34b_XL.jpg');
INSERT INTO `picname` VALUES ('12', '0_7fb31_e3cdcd1c_XL.jpg');
INSERT INTO `picname` VALUES ('13', '0_7fb32_6b460545_XL.jpg');
INSERT INTO `picname` VALUES ('14', '0_7fb33_acd6739a_XL.jpg');
INSERT INTO `picname` VALUES ('15', '0_7fb34_ab00bf67_XL.jpg');
INSERT INTO `picname` VALUES ('16', '0_7fb3e_113976f_XL.jpg');
INSERT INTO `picname` VALUES ('17', '0_7fb3f_94efd114_XL.jpg');
INSERT INTO `picname` VALUES ('18', '0_7fb40_5b6d233a_XL.jpg');
INSERT INTO `picname` VALUES ('19', '0_7fb41_12bc8920_XL.jpg');
INSERT INTO `picname` VALUES ('20', '0_7fb42_90681da0_XL.jpg');
INSERT INTO `picname` VALUES ('21', '0_7fb43_905bc0f3_XL.jpg');
INSERT INTO `picname` VALUES ('22', '0_7fb44_90930a2a_XL.jpg');
INSERT INTO `picname` VALUES ('23', '0_7fb45_a6805d76_XL.jpg');
INSERT INTO `picname` VALUES ('24', '0_7fb46_225ea88c_XL.jpg');
INSERT INTO `picname` VALUES ('25', '0_7fb47_2f06130c_XL.jpg');
INSERT INTO `picname` VALUES ('26', '0_7fb48_8c86d0c3_XL.jpg');
INSERT INTO `picname` VALUES ('27', '0_7fb49_f257bfaa_XL.jpg');
INSERT INTO `picname` VALUES ('28', '0_7fb4a_afd1aa87_XL.jpg');
INSERT INTO `picname` VALUES ('29', '0_7fb4b_eaecc1c_XL.jpg');
INSERT INTO `picname` VALUES ('30', '0_813d2_6e62276c_orig.jpg');
INSERT INTO `picname` VALUES ('31', '0_813d3_41b0aa73_orig.jpg');
INSERT INTO `picname` VALUES ('32', '0_813d4_3ba3df25_orig.jpg');
INSERT INTO `picname` VALUES ('33', '0_813d5_a340c8dc_orig.jpg');
INSERT INTO `picname` VALUES ('34', '0_813d6_b979584e_orig.jpg');
INSERT INTO `picname` VALUES ('35', '0_813d7_a0a3f6a4_orig.jpg');
INSERT INTO `picname` VALUES ('36', '0_813d8_a68c7c8a_orig.jpg');
INSERT INTO `picname` VALUES ('37', '0_813d9_343a00fa_orig.jpg');
INSERT INTO `picname` VALUES ('38', '0_813da_8f97b592_orig.jpg');
INSERT INTO `picname` VALUES ('39', '0_813db_aeb4709e_orig.jpg');
INSERT INTO `picname` VALUES ('40', '0_813dc_c7612714_orig.jpg');
INSERT INTO `picname` VALUES ('41', '0_813e3_1492230d_orig.jpg');
INSERT INTO `picname` VALUES ('42', '0_813e4_6de08399_orig.jpg');
INSERT INTO `picname` VALUES ('43', '0_813e5_f0caf45b_orig.jpg');
INSERT INTO `picname` VALUES ('44', '0_813e6_52aa9d87_orig.jpg');
INSERT INTO `picname` VALUES ('45', '0_813e7_111000b2_orig.jpg');
INSERT INTO `picname` VALUES ('46', '0_813e8_a16497fa_orig.jpg');
INSERT INTO `picname` VALUES ('47', '0_813e9_181994c5_orig.jpg');
INSERT INTO `picname` VALUES ('48', '0_813ea_be70d086_orig.jpg');
INSERT INTO `picname` VALUES ('49', '0_813eb_a7c324cd_orig.jpg');
INSERT INTO `picname` VALUES ('50', '0_813ec_7368b76e_orig.jpg');
INSERT INTO `picname` VALUES ('51', '0_813ed_a21724f5_orig.jpg');
INSERT INTO `picname` VALUES ('52', '0_813ee_d9f21100_orig.jpg');
INSERT INTO `picname` VALUES ('53', '0_813ef_e2f8f6a3_orig.jpg');
INSERT INTO `picname` VALUES ('54', '0_813f0_cb09cdbe_orig.jpg');
INSERT INTO `picname` VALUES ('55', '0_813f1_e6302087_orig.jpg');
INSERT INTO `picname` VALUES ('56', '0_813f2_6bc359f8_orig.jpg');
INSERT INTO `picname` VALUES ('57', '0_813f3_16f9a8ef_orig.jpg');
INSERT INTO `picname` VALUES ('58', '0_813f4_f57be914_orig.jpg');
INSERT INTO `picname` VALUES ('59', '0_813f5_8e6ab8c1_orig.jpg');
INSERT INTO `picname` VALUES ('60', '0_813f6_7352ab51_orig.jpg');
INSERT INTO `picname` VALUES ('61', '0_813f7_5bf6003b_orig.jpg');
INSERT INTO `picname` VALUES ('62', '0_813f8_4dbbf9d6_orig.jpg');
INSERT INTO `picname` VALUES ('63', '0_813f9_58147950_orig.jpg');
INSERT INTO `picname` VALUES ('64', '0_813fa_a2ba32db_orig.jpg');
INSERT INTO `picname` VALUES ('65', '0_813fb_92cc11d1_orig.jpg');
INSERT INTO `picname` VALUES ('66', '0_813fc_9f11a7c8_orig.jpg');
INSERT INTO `picname` VALUES ('67', '0_813fd_af295cf6_orig.jpg');
INSERT INTO `picname` VALUES ('68', '0_813fe_206bc6e0_orig.jpg');
INSERT INTO `picname` VALUES ('69', '0_813ff_311d1ec7_orig.jpg');
INSERT INTO `picname` VALUES ('70', '0_81400_e44b2c6d_orig.jpg');
INSERT INTO `picname` VALUES ('71', '0_81401_f6887ba6_orig.jpg');
INSERT INTO `picname` VALUES ('72', '0_81402_18c9c707_orig.jpg');
INSERT INTO `picname` VALUES ('73', '0_81621_e073d55f_orig.jpg');
INSERT INTO `picname` VALUES ('74', '0_81622_1702accd_orig.jpg');
INSERT INTO `picname` VALUES ('75', '0_81623_7d23a7c7_orig.jpg');
INSERT INTO `picname` VALUES ('76', '0_81624_aae59692_orig.jpg');
INSERT INTO `picname` VALUES ('77', '0_81625_48dee38b_orig.jpg');
INSERT INTO `picname` VALUES ('78', '0_81626_d1e8091c_orig.jpg');
INSERT INTO `picname` VALUES ('79', '0_81627_50dfe031_orig.jpg');
INSERT INTO `picname` VALUES ('80', '0_81628_7ba38878_orig.jpg');
INSERT INTO `picname` VALUES ('81', '0_81629_5efc0654_orig.jpg');
INSERT INTO `picname` VALUES ('82', '0_8162a_c1c1b3c3_orig.jpg');
INSERT INTO `picname` VALUES ('83', '0_8162b_f1c87ea0_orig.jpg');
INSERT INTO `picname` VALUES ('84', '0_8162c_367e3fd8_orig.jpg');
INSERT INTO `picname` VALUES ('85', '0_8162d_46a6b4eb_orig.jpg');
INSERT INTO `picname` VALUES ('86', '0_8162e_86724849_orig.jpg');
INSERT INTO `picname` VALUES ('87', '0_82064_6281aa25_XL.jpg');
INSERT INTO `picname` VALUES ('88', '0_82065_81c79717_XL.jpg');
INSERT INTO `picname` VALUES ('89', '0_82066_63dfe1e1_XL.jpg');
INSERT INTO `picname` VALUES ('90', '0_82067_26535195_XL.jpg');
INSERT INTO `picname` VALUES ('91', '0_82068_39c59af9_XL.jpg');
INSERT INTO `picname` VALUES ('92', '0_82069_e95369ab_XL.jpg');
INSERT INTO `picname` VALUES ('93', '0_8206a_308b9143_XL.jpg');
INSERT INTO `picname` VALUES ('94', '0_8206b_e020808b_XL.jpg');
INSERT INTO `picname` VALUES ('95', '0_8206c_ebd48734_XL.jpg');
INSERT INTO `picname` VALUES ('96', '0_8206d_df8e351_XL.jpg');
INSERT INTO `picname` VALUES ('97', '0_8206e_e02a3937_XL.jpg');
INSERT INTO `picname` VALUES ('98', '0_8206f_6b41bee2_XL.jpg');
INSERT INTO `picname` VALUES ('99', '0_82070_a43fef4e_XL.jpg');
INSERT INTO `picname` VALUES ('100', '0_82071_19b9250f_XL.jpg');
INSERT INTO `picname` VALUES ('101', '0_82072_76ac60ed_XL.jpg');
INSERT INTO `picname` VALUES ('102', '0_82073_10f3ab0c_XL.jpg');
INSERT INTO `picname` VALUES ('103', '0_82074_35ce7541_XL.jpg');
INSERT INTO `picname` VALUES ('104', '0_82075_1ce0f749_XL.jpg');
INSERT INTO `picname` VALUES ('105', '0_82076_3139dc1b_XL.jpg');
INSERT INTO `picname` VALUES ('106', '0_82077_e0697e26_XL.jpg');
INSERT INTO `picname` VALUES ('107', '0_82078_3fcbebf7_XL.jpg');
INSERT INTO `picname` VALUES ('108', '0_82079_fd081c80_XL.jpg');
INSERT INTO `picname` VALUES ('109', '0_8207a_4417f16d_XL.jpg');
INSERT INTO `picname` VALUES ('110', '0_92017_31a7b85d_L.jpg');
INSERT INTO `picname` VALUES ('111', '0_92019_7a23f187_XL.jpg');
INSERT INTO `picname` VALUES ('112', '0_9201a_9f4f1723_L.jpg');
INSERT INTO `picname` VALUES ('113', '0_9201c_cd10b075_L.jpg');
INSERT INTO `picname` VALUES ('114', '0_9201d_487fffe2_XL.jpg');
INSERT INTO `picname` VALUES ('115', '0_9201f_90f79e79_L.jpg');
INSERT INTO `picname` VALUES ('116', '0_92021_dbffaecb_L.jpg');
INSERT INTO `picname` VALUES ('117', '0_92022_ad492340_XL.jpg');
INSERT INTO `picname` VALUES ('118', '0_92024_a1393477_XL.jpg');
INSERT INTO `picname` VALUES ('119', '0_92025_e912d787_XL.jpg');
INSERT INTO `picname` VALUES ('120', '30129261.jpg');
INSERT INTO `picname` VALUES ('121', '460.jpg');
INSERT INTO `picname` VALUES ('122', '4600.jpg');
INSERT INTO `picname` VALUES ('123', '4607.jpg');
INSERT INTO `picname` VALUES ('124', '460sas.jpg');
INSERT INTO `picname` VALUES ('125', '4620.jpg');
INSERT INTO `picname` VALUES ('126', '4645550.jpg');
INSERT INTO `picname` VALUES ('127', 'close.png');
INSERT INTO `picname` VALUES ('128', 'ps54646b.jpg');
INSERT INTO `picname` VALUES ('129', 'psb (1).jpg');
INSERT INTO `picname` VALUES ('130', 'psb (1656).jpg');
INSERT INTO `picname` VALUES ('131', 'www.loveqzone.net (1).gif');
INSERT INTO `picname` VALUES ('132', 'www.loveqzone.net (1).jpg');
INSERT INTO `picname` VALUES ('133', 'www.loveqzone.net (10).jpg');
INSERT INTO `picname` VALUES ('134', 'www.loveqzone.net (100).jpg');
INSERT INTO `picname` VALUES ('135', 'www.loveqzone.net (101).jpg');
INSERT INTO `picname` VALUES ('136', 'www.loveqzone.net (102).jpg');
INSERT INTO `picname` VALUES ('137', 'www.loveqzone.net (103).jpg');
INSERT INTO `picname` VALUES ('138', 'www.loveqzone.net (104).jpg');
INSERT INTO `picname` VALUES ('139', 'www.loveqzone.net (105).jpg');
INSERT INTO `picname` VALUES ('140', 'www.loveqzone.net (106).jpg');
INSERT INTO `picname` VALUES ('141', 'www.loveqzone.net (107).jpg');
INSERT INTO `picname` VALUES ('142', 'www.loveqzone.net (108).jpg');
INSERT INTO `picname` VALUES ('143', 'www.loveqzone.net (109).jpg');
INSERT INTO `picname` VALUES ('144', 'www.loveqzone.net (11).jpg');
INSERT INTO `picname` VALUES ('145', 'www.loveqzone.net (110).jpg');
INSERT INTO `picname` VALUES ('146', 'www.loveqzone.net (111).jpg');
INSERT INTO `picname` VALUES ('147', 'www.loveqzone.net (112).jpg');
INSERT INTO `picname` VALUES ('148', 'www.loveqzone.net (113).jpg');
INSERT INTO `picname` VALUES ('149', 'www.loveqzone.net (114).jpg');
INSERT INTO `picname` VALUES ('150', 'www.loveqzone.net (115).jpg');
INSERT INTO `picname` VALUES ('151', 'www.loveqzone.net (116).jpg');
INSERT INTO `picname` VALUES ('152', 'www.loveqzone.net (117).jpg');
INSERT INTO `picname` VALUES ('153', 'www.loveqzone.net (118).jpg');
INSERT INTO `picname` VALUES ('154', 'www.loveqzone.net (119).jpg');
INSERT INTO `picname` VALUES ('155', 'www.loveqzone.net (12).jpg');
INSERT INTO `picname` VALUES ('156', 'www.loveqzone.net (120).jpg');
INSERT INTO `picname` VALUES ('157', 'www.loveqzone.net (121).jpg');
INSERT INTO `picname` VALUES ('158', 'www.loveqzone.net (122).jpg');
INSERT INTO `picname` VALUES ('159', 'www.loveqzone.net (123).jpg');
INSERT INTO `picname` VALUES ('160', 'www.loveqzone.net (13).jpg');
INSERT INTO `picname` VALUES ('161', 'www.loveqzone.net (14).jpg');
INSERT INTO `picname` VALUES ('162', 'www.loveqzone.net (15).jpg');
INSERT INTO `picname` VALUES ('163', 'www.loveqzone.net (16).jpg');
INSERT INTO `picname` VALUES ('164', 'www.loveqzone.net (17).jpg');
INSERT INTO `picname` VALUES ('165', 'www.loveqzone.net (18).jpg');
INSERT INTO `picname` VALUES ('166', 'www.loveqzone.net (19).jpg');
INSERT INTO `picname` VALUES ('167', 'www.loveqzone.net (2).gif');
INSERT INTO `picname` VALUES ('168', 'www.loveqzone.net (2).jpg');
INSERT INTO `picname` VALUES ('169', 'www.loveqzone.net (20).jpg');
INSERT INTO `picname` VALUES ('170', 'www.loveqzone.net (21).jpg');
INSERT INTO `picname` VALUES ('171', 'www.loveqzone.net (22).jpg');
INSERT INTO `picname` VALUES ('172', 'www.loveqzone.net (23).jpg');
INSERT INTO `picname` VALUES ('173', 'www.loveqzone.net (24).jpg');
INSERT INTO `picname` VALUES ('174', 'www.loveqzone.net (25).jpg');
INSERT INTO `picname` VALUES ('175', 'www.loveqzone.net (26).jpg');
INSERT INTO `picname` VALUES ('176', 'www.loveqzone.net (27).jpg');
INSERT INTO `picname` VALUES ('177', 'www.loveqzone.net (28).jpg');
INSERT INTO `picname` VALUES ('178', 'www.loveqzone.net (29).jpg');
INSERT INTO `picname` VALUES ('179', 'www.loveqzone.net (3).jpg');
INSERT INTO `picname` VALUES ('180', 'www.loveqzone.net (30).jpg');
INSERT INTO `picname` VALUES ('181', 'www.loveqzone.net (31).jpg');
INSERT INTO `picname` VALUES ('182', 'www.loveqzone.net (32).jpg');
INSERT INTO `picname` VALUES ('183', 'www.loveqzone.net (33).jpg');
INSERT INTO `picname` VALUES ('184', 'www.loveqzone.net (34).jpg');
INSERT INTO `picname` VALUES ('185', 'www.loveqzone.net (35).jpg');
INSERT INTO `picname` VALUES ('186', 'www.loveqzone.net (36).jpg');
INSERT INTO `picname` VALUES ('187', 'www.loveqzone.net (37).jpg');
INSERT INTO `picname` VALUES ('188', 'www.loveqzone.net (38).jpg');
INSERT INTO `picname` VALUES ('189', 'www.loveqzone.net (39).jpg');
INSERT INTO `picname` VALUES ('190', 'www.loveqzone.net (4).jpg');
INSERT INTO `picname` VALUES ('191', 'www.loveqzone.net (40).jpg');
INSERT INTO `picname` VALUES ('192', 'www.loveqzone.net (41).jpg');
INSERT INTO `picname` VALUES ('193', 'www.loveqzone.net (42).jpg');
INSERT INTO `picname` VALUES ('194', 'www.loveqzone.net (43).jpg');
INSERT INTO `picname` VALUES ('195', 'www.loveqzone.net (44).jpg');
INSERT INTO `picname` VALUES ('196', 'www.loveqzone.net (45).jpg');
INSERT INTO `picname` VALUES ('197', 'www.loveqzone.net (46).jpg');
INSERT INTO `picname` VALUES ('198', 'www.loveqzone.net (47).jpg');
INSERT INTO `picname` VALUES ('199', 'www.loveqzone.net (48).jpg');
INSERT INTO `picname` VALUES ('200', 'www.loveqzone.net (49).jpg');
INSERT INTO `picname` VALUES ('201', 'www.loveqzone.net (5).jpg');
INSERT INTO `picname` VALUES ('202', 'www.loveqzone.net (50).jpg');
INSERT INTO `picname` VALUES ('203', 'www.loveqzone.net (51).jpg');
INSERT INTO `picname` VALUES ('204', 'www.loveqzone.net (52).jpg');
INSERT INTO `picname` VALUES ('205', 'www.loveqzone.net (53).jpg');
INSERT INTO `picname` VALUES ('206', 'www.loveqzone.net (54).jpg');
INSERT INTO `picname` VALUES ('207', 'www.loveqzone.net (55).jpg');
INSERT INTO `picname` VALUES ('208', 'www.loveqzone.net (56).jpg');
INSERT INTO `picname` VALUES ('209', 'www.loveqzone.net (57).jpg');
INSERT INTO `picname` VALUES ('210', 'www.loveqzone.net (58).jpg');
INSERT INTO `picname` VALUES ('211', 'www.loveqzone.net (59).jpg');
INSERT INTO `picname` VALUES ('212', 'www.loveqzone.net (6).jpg');
INSERT INTO `picname` VALUES ('213', 'www.loveqzone.net (60).jpg');
INSERT INTO `picname` VALUES ('214', 'www.loveqzone.net (61).jpg');
INSERT INTO `picname` VALUES ('215', 'www.loveqzone.net (62).jpg');
INSERT INTO `picname` VALUES ('216', 'www.loveqzone.net (63).jpg');
INSERT INTO `picname` VALUES ('217', 'www.loveqzone.net (64).jpg');
INSERT INTO `picname` VALUES ('218', 'www.loveqzone.net (65).jpg');
INSERT INTO `picname` VALUES ('219', 'www.loveqzone.net (66).jpg');
INSERT INTO `picname` VALUES ('220', 'www.loveqzone.net (67).jpg');
INSERT INTO `picname` VALUES ('221', 'www.loveqzone.net (68).jpg');
INSERT INTO `picname` VALUES ('222', 'www.loveqzone.net (69).jpg');
INSERT INTO `picname` VALUES ('223', 'www.loveqzone.net (7).jpg');
INSERT INTO `picname` VALUES ('224', 'www.loveqzone.net (70).jpg');
INSERT INTO `picname` VALUES ('225', 'www.loveqzone.net (71).jpg');
INSERT INTO `picname` VALUES ('226', 'www.loveqzone.net (72).jpg');
INSERT INTO `picname` VALUES ('227', 'www.loveqzone.net (73).jpg');
INSERT INTO `picname` VALUES ('228', 'www.loveqzone.net (74).jpg');
INSERT INTO `picname` VALUES ('229', 'www.loveqzone.net (75).jpg');
INSERT INTO `picname` VALUES ('230', 'www.loveqzone.net (76).jpg');
INSERT INTO `picname` VALUES ('231', 'www.loveqzone.net (77).jpg');
INSERT INTO `picname` VALUES ('232', 'www.loveqzone.net (78).jpg');
INSERT INTO `picname` VALUES ('233', 'www.loveqzone.net (79).jpg');
INSERT INTO `picname` VALUES ('234', 'www.loveqzone.net (8).jpg');
INSERT INTO `picname` VALUES ('235', 'www.loveqzone.net (80).jpg');
INSERT INTO `picname` VALUES ('236', 'www.loveqzone.net (81).jpg');
INSERT INTO `picname` VALUES ('237', 'www.loveqzone.net (82).jpg');
INSERT INTO `picname` VALUES ('238', 'www.loveqzone.net (83).jpg');
INSERT INTO `picname` VALUES ('239', 'www.loveqzone.net (84).jpg');
INSERT INTO `picname` VALUES ('240', 'www.loveqzone.net (85).jpg');
INSERT INTO `picname` VALUES ('241', 'www.loveqzone.net (86).jpg');
INSERT INTO `picname` VALUES ('242', 'www.loveqzone.net (87).jpg');
INSERT INTO `picname` VALUES ('243', 'www.loveqzone.net (88).jpg');
INSERT INTO `picname` VALUES ('244', 'www.loveqzone.net (89).jpg');
INSERT INTO `picname` VALUES ('245', 'www.loveqzone.net (9).jpg');
INSERT INTO `picname` VALUES ('246', 'www.loveqzone.net (90).jpg');
INSERT INTO `picname` VALUES ('247', 'www.loveqzone.net (91).jpg');
INSERT INTO `picname` VALUES ('248', 'www.loveqzone.net (92).jpg');
INSERT INTO `picname` VALUES ('249', 'www.loveqzone.net (93).jpg');
INSERT INTO `picname` VALUES ('250', 'www.loveqzone.net (94).jpg');
INSERT INTO `picname` VALUES ('251', 'www.loveqzone.net (95).jpg');
INSERT INTO `picname` VALUES ('252', 'www.loveqzone.net (96).jpg');
INSERT INTO `picname` VALUES ('253', 'www.loveqzone.net (97).jpg');
INSERT INTO `picname` VALUES ('254', 'www.loveqzone.net (98).jpg');
INSERT INTO `picname` VALUES ('255', 'www.loveqzone.net (99).jpg');

-- ----------------------------
-- Table structure for `weibo`
-- ----------------------------
DROP TABLE IF EXISTS `weibo`;
CREATE TABLE `weibo` (
  `id` int(12) NOT NULL AUTO_INCREMENT,
  `weibo` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=445 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of weibo
-- ----------------------------
INSERT INTO `weibo` VALUES ('1', '有些故事，不一定要讲给所有人听；有些悲伤，不一定谁都会懂；有些伤口，时间久了就会慢慢长好；有些委屈，受过了想通了也就释然了；有些伤痛，忍过了疼久了也成习惯了；有些藏在心底的话，不想说也就没必要说了。其实，并不是所有的痛，都可以呐喊；不是所有的爱，都可以表白。');
INSERT INTO `weibo` VALUES ('2', '爱在微BO蔓延时: 没有什么决定是可以两全的，如果总是这样，你永远做不出什么决定。当你最终顺了自己的心，而不是遵循生活的习惯，我自己选择了方向与路途时，你就不要抱怨。一个人只有承担起旅途风雨，才能最终守得住彩虹满天，桃花源因你而存在，彼岸花为你而盛开。');
INSERT INTO `weibo` VALUES ('3', '草根语录: 有些事注定成为故事，有些人注定成为故人，有些路注定要一个人走。一些人，一些事，闯进生活，得到了，失去的，昨天的悲伤，今天的快乐，喜怒哀乐都要记得。当这一切都成了回忆，在我们记忆中又会留下了什么？很多事，过去了，很多人，离开了，经历的多了，心就坚强了，路就踏实了。');
INSERT INTO `weibo` VALUES ('4', '经典语录: 不再留着你的短信不舍得删掉了，不再一遍一遍的回看我们的聊天记录了，不再眼巴巴的盯着手机期望你的电话了，不再上一整晚的QQ等你现身了，不再到处跟别人打听你的消息了，不再向好友倾诉自己的心酸了，因为倾诉过一次，已经代表，我决定放下你了');
INSERT INTO `weibo` VALUES ('5', '夜空上的流星: 当明天变成了今天成为了昨天，最后成为记忆里不再重要的某一天，我们突然发现自己在不知不觉中已被时间推着向前走，这不是静止火车里，与相邻列车交错时，仿佛自己在前进的错觉，而是我们真实的在成长，在这件事里成了另一个自己。');
INSERT INTO `weibo` VALUES ('6', '加措活佛-慈爱基金: 学会知而不言，因为言多必失；学会自我解脱，因为这样才能自我超越；学会一个人静静思考，因为这样才能让自己更清醒、明白；学会用心看世界，因为这样才会看清人的本来面目；学会放下，因为只有放下了才能重新开始；学会感恩，因为拥有一颗感恩的心能帮助我们在逆境中寻求希望，在悲观中寻求快乐');
INSERT INTO `weibo` VALUES ('7', '精彩语录: 成功男人的标志：3岁，不尿裤子；5岁，能自己吃饭；18岁，能自己开车；20岁，有性生活；30岁，有钱；40岁，有钱；50岁，有钱；60岁，有性生活；70岁，能自己开车；80岁，能自己吃饭；90岁，不尿裤子。人生就是一个轮回。');
INSERT INTO `weibo` VALUES ('8', '天使不在的13月丶: 任何人所拥有的一切，与有大美而不言的天地相比，与浩瀚无际的宇宙相比，都不如沧海一粟，实在是微不足道。从历史的长河来看，不管我们拥有什么，拥有多少、拥有多久，都只不过是拥有极其渺小的瞬间。人誉我谦，又增一美；自夸自败，又增一毁。无论何时何地，我们永远都应保持一颗谦卑的心。');
INSERT INTO `weibo` VALUES ('9', '她说: 【那些你需要记心里的话】1、放弃留不住的人。留住了个别人，也许会失去一群人。2、自己一定要在乎自尊，你的自尊在别人眼里一钱不值。3、可以不把别人当朋友，也别把别人当敌人。4、一生会有很多诱惑，自己一定要有个底限。5、我们必须接受失望，因为它是有限的，但千万不可失去希望，因为它是无穷的.');
INSERT INTO `weibo` VALUES ('10', '姜小琳: 【珍惜现在】知道时间不可能停留,就没有必要伤春悲秋；知道感情不可能勉强,就不会为了谁深情挽留；知道孤独总是如影随形,就不会在某一些时刻难以自制；知道遗忘总是必然,就不会为一时的思念而伤感；知道回忆始终是存在的,就没有必要故意的遮掩；知道所有的美好总会消逝,就一定要尽量把握住眼前 \n');
INSERT INTO `weibo` VALUES ('11', ' \n一种酒喝出四种味道：友情、亲情、感情、凄情。一种酒喝出几种感觉：浪漫、优雅、舒适、人生。一个地方触发四种的感受范围：开心、文雅、奢侈、伤悲。一个人应有四种原则：守则、规则、原则、知则。人的性格可放纵、可任性、可闹剧，但是不可背弃最基本的尊重。我的最爱：赛拉图，你是那么的醇香甜。  \n');
INSERT INTO `weibo` VALUES ('12', ' \n从来没有想过有一天我会如此在乎你，不管我们的结局是否完美我都不会放弃，想用一生来换取这种感觉，我会把你一辈子放在心里，无论你喜欢谁，在你的心里给我留一个位子，我真的好累，好想停下来休息，却又怕跟丢了你，那么的爱你，不想放弃..');
INSERT INTO `weibo` VALUES ('13', '80年代80年代:小时候，希望自己快点长大，长大了，却发现遗失了童年；单身时，开始羡慕恋人的甜蜜，恋爱时，怀念单身时的自由。很多事物，没有得到时总觉得美好，得到之后才开始明白：我们得到的同时也是在失去。');
INSERT INTO `weibo` VALUES ('14', ' \n你以后会明白，如果世界上曾经有那个人出现过，其他人都会变成将就。我不愿意将就。');
INSERT INTO `weibo` VALUES ('15', ' \n曾经，为谁放肆的哭泣.你是吹进我眼里的沙子，模糊了双眼，看不清天空的样子。 这一场末路繁华，不倾城，不倾国，却倾我所有。 你要的是什么。一生相守。还是一晌贪欢。 我要的。只是简单却安稳的生活而已。 爱到绝路，覆水难收。 最好的幸福，是你给的在乎。');
INSERT INTO `weibo` VALUES ('16', ' \n不再留着你的短信不舍得删掉了，不再一遍一遍的回看我们的聊天记录了，不再眼巴巴的盯着手机期望你的电话了，不再上一整晚的QQ等你现身了，不再到处跟别人打听你的消息了，不再向好友倾诉自己的心酸了，因为倾诉过一次，已经代表，我决定放下你了。');
INSERT INTO `weibo` VALUES ('17', '1、QQ天天在线，说明你害怕孤独。2、QQ天天隐身，说明你承认孤独。3、QQ天天忙碌，说明你装不孤独。4、QQ天天离开，说明你暗示孤独。');
INSERT INTO `weibo` VALUES ('18', 'A smile is the shortest distance between two people. - 微笑是两个人之间最短的距离。');
INSERT INTO `weibo` VALUES ('19', '小时候，希望自己快点长大，长大了，却发现遗失了童年；单身时，开始羡慕恋人的甜；恋爱时，怀念单身时的自由。很多事物，没有得到时总觉得美好，得到之后才开始明白：原来我们在得到的同时，也在失去。');
INSERT INTO `weibo` VALUES ('20', '当一个男人不爱女人的时候，她做什么都是错的。你对他好是错的，你对他不好更是错。当一个女人不爱男人的时候，他的任何关心也都是错，甚至是被厌恶的，他的等待、他的哀求，甚至他的哭泣，丝毫不能挽回女人的心，反而成了女人厌倦他的另一个理由：婆婆妈妈的男人，和他恋爱起来又有什么意思？');
INSERT INTO `weibo` VALUES ('21', '精辟：水浒:我砍；西游:我变；三国:我哭；红楼:我曰！西游:取到了；红楼:家败了；水浒:死光了；三国:统一了！水浒:俺江湖上有人；红楼:俺朝廷里有人；西游:俺天上有人；三国:俺有得是人！水浒:大部分是男人；红楼：大部分是女人；西游:大部分不是人；三国:大部分全是人！');
INSERT INTO `weibo` VALUES ('22', '1.原来，我们这些人的青春，每一个人都是暗伤连城。2.这个世界上很多的事,不能深究,往往没有我们自己想要的结果，捧着鲜血淋漓的真相，终究是一声唏嘘.3.最好的年华要给最好的人，我们已经错过了4.你来过一下子，我想念一辈子。5我放下了尊严，放下了个性，放下了固执，都只是因为放不下你');
INSERT INTO `weibo` VALUES ('23', '天蝎不喜欢浮华的爱情，只想平淡地爱，但要刻骨铭心。');
INSERT INTO `weibo` VALUES ('24', '天蝎有时的想法很极端，比如和恋人正好好的，他/她还会想：假如有一天要是分手了，对方也会很后悔，因为自己给对方的爱是别人代替不了的。');
INSERT INTO `weibo` VALUES ('25', '天蝎不喜欢争吵，大多数情况下会用沉默来代替内心的不良情绪。但若遇到十分气恼的情况，他/她会发威，结果是口不择言，不用费劲地说世界上最恶毒的语言说出来给对方听，中伤对方。但过不了两天，天蝎自己会主动反省，为自己的言语感到失态和后悔。 ');
INSERT INTO `weibo` VALUES ('26', '天蝎喜欢钻牛角尖，同一件事情发生后，到天蝎这里就被他们多想了三圈，而那些冒出来的想法大都是胡思乱想的结果，最终天蝎自己还会反问：为什么会是这样呢？其实他们所想的事根本就没发生。有点古怪哦！');
INSERT INTO `weibo` VALUES ('27', '天蝎怕孤独，对于感情也十分敏感，对方的一个小小的动作或眼神，他们都会看在眼里记在心里，接下来的事情就是天蝎开始猜想对方的心思了，猜来猜去，是为了让对方感觉到自己的用心良苦和自己对恋人深刻的爱。 ');
INSERT INTO `weibo` VALUES ('28', '天蝎不喜欢向恋人说出自己的一些想法，因为害羞或是别的什么原因，天蝎自己也说不好。他们更喜欢或是希望对方能猜出他们的心思来，若对方没有能猜中天蝎的想法，天蝎便会对恋人很失望，觉得恋人不了解自己。 ');
INSERT INTO `weibo` VALUES ('29', '天蝎座的人有一点刘若英为爱痴狂里的那种人的特点，对待爱情是傻傻的，直直的。总之，如果你爱天蝎的话，他/她表面的所作所为只是为了证明他/她是多么地爱你。珍惜天蝎的爱吧，因为他们是很认真的在爱着你。');
INSERT INTO `weibo` VALUES ('30', '天蝎的他/她很希望能和对方有默契，达到共识。于是便会做一些近乎讨好对方的事情，但这并不能算是卑微，哪怕最后只得来对方一个甜甜的笑，对于他们来说，就是一种莫大的满足和成就。');
INSERT INTO `weibo` VALUES ('31', '天蝎平常的脾气是典型的外冷内热，但能被他们热到的人并不多，越是天蝎表面对你很热情的话，那大都能证明一点，他/她对你没有太大的兴趣。反之，表面上对你带搭不理，其实内心已经在向你靠近了，当然也不是每次都是这样，这就要看你的眼力了。说不定天蝎烦你烦得要死，连那份表面的热情也赖得装给你看。 ');
INSERT INTO `weibo` VALUES ('32', '不得不讲的是，天蝎座的人有时有些神精质，自愚的能力也挺强。从他们嘴里可以不太困难地听到一些奇怪的话，他们不以为然，也不会理会恋人听到这些话之后的反应。 ');
INSERT INTO `weibo` VALUES ('33', '天蝎的人很怕自己身边有亲密关系人的否定，比如家人恋人对他们的一些指责或是批评，并不是天蝎不勇于承认错误，而是他们认为连自己身边的人都不信任自己，这会使他们暗自很伤心 ');
INSERT INTO `weibo` VALUES ('34', '天蝎爱起来就像火山爆发，恨起来就像冰山一角。这个还是有些道理的，天蝎的爱有时会让对方受宠若惊，甚至有些防不胜防的感觉。 ');
INSERT INTO `weibo` VALUES ('35', '天蝎天生就有一种保护人的欲望，外出购物的时候他们的本能是要首先掏腰包的，不是虚荣，而是一种给自己自信的途径，看到对方满足的样子便倍有成就感。总之他们喜欢自己处于强势。 ');
INSERT INTO `weibo` VALUES ('36', '天蝎很少会对人说：求这个字。因为他们觉得求人不好，好像会影响自己的形象，所以宁可这件事不做了，也不会轻易开口向别人求助，他们只是不想欠别人的。');
INSERT INTO `weibo` VALUES ('37', '天蝎有些自我折磨的倾向，一旦失恋之后，便会多日走不出失恋的阴影。内心渴望着对方能回心转意，当然是在对方先提出分手的情况下，虽然如此，倘若真的对方有所回头，天蝎又会因为那骨子里天生的冷酷而断然拒绝对方。 ');
INSERT INTO `weibo` VALUES ('38', '天蝎在一些事情上是有预感的，即使有些事恋人没有如实地讲出来，天蝎的他/她却早已了解实情，但却不会当面揭穿恋人，内心还会有些得意，认为对方的小伎俩小想法早已尽在自己的掌握之中。 ');
INSERT INTO `weibo` VALUES ('39', '天蝎在和恋人在一起时，就会变得很傻，傻到好像世界是静止的一样，他/她可能不会考虑任何现实中会发生的事情，以及周围人对他们的看法。彷拂天蝎一和恋人见面，便会钻进一个不透明的盒子里，傻傻的，还算是傻得可爱吧。');
INSERT INTO `weibo` VALUES ('40', '当天蝎和自己的恋人闹别扭时，开始的时候他们会很坚决，大有一种决不首先向对方妥协的势气。时间一久，天蝎就开始想对方的好了，于是自己主动找上门和恋人和好如初就像什么都没有发生过。虽然蝎子的内心是有些气的，但一见到恋人就又“傻”过去了，这就是我所了解的天蝎，自我矛盾加自我折磨的天蝎。 ');
INSERT INTO `weibo` VALUES ('41', '天蝎座有时会宠坏了恋人，即使一个天蝎的女生也会像个“男生”一样宠着自己的恋人，难怪网上有种说法说天蝎座的女生能活得像个男生一样，因为好多事她们完全有能力处理和解决，甚至是在男友面前也会抑制不住自己去做一些该由男生来做的事。');
INSERT INTO `weibo` VALUES ('42', '天蝎MM不喜欢在男人面前示弱，即使这件事本该男人来做，但当她们看到自己的男人在做事的时候不足够利落和潇洒时，她们便会忍不住去揽下来，自己做。');
INSERT INTO `weibo` VALUES ('43', '天蝎对恋人正面的批评很反感，甚至是恼怒。并不是不愿意听恋人的劝告，因为那些批评的语言会让他们觉得对方是在羞辱自己，如果对方以一种开玩笑的语气讲他们的缺点，他们会更乐意接受并且在内心感激恋人的包容。');
INSERT INTO `weibo` VALUES ('44', '天蝎女生表面坚强，嘴巴硬，说话狠。其实内心很容易受到伤害。当自己的恋人做了让她们很难过的事，她们心里默默地难过，感觉自己像个受伤的，却勇敢站在人群中的雕像一样，漠然地看着身边那些恋人们的甜蜜欢笑。这时的天蝎说话比平常少得多，没有心情再像平时那样和周围的人谈笑风声。 ');
INSERT INTO `weibo` VALUES ('45', '当发现周围的人都躲着天蝎的时候，天蝎们也觉得很好笑，可能有的人还会认为天蝎是个怪人，有点喜怒无常的感觉，这一点虽然不及巨蟹那么明显。蝎子心里倒会想的是，这样也挺好的，省掉了和身边的人应付的话语，只是孤独多了一些。');
INSERT INTO `weibo` VALUES ('46', '天蝎的同性朋友并不是很多，因为他们对朋友的定义好像有点严格了，那种酒肉朋友他们是决不看在眼里的，就算表面上和你有说有笑，内心却厌恶得要死。他们当然能很清楚地知道自己需要什么样的人来做朋友，只有那些有信誉够义气很少玩嘴的人，才会让天蝎放下心来和他们做交心的朋友。顺便说一句：天蝎对自己的朋友是很好的，自己吃一些亏也无所谓，只要朋友能在他们需要的时候陪他们聊聊就足够。对于朋友的一些事情，他们也会当做是自己的事情一样，热心去帮助对方。如果你身边有一个天蝎的好朋友的话，应该是比较幸福的哦！');
INSERT INTO `weibo` VALUES ('47', '再说说天蝎的异性朋友吧，在没有正式的男友或女友之前，天蝎的异性朋友还是不少的。因为他们觉得那是一种象征，象征自己是惹人喜爱的。这句话有点儿过头！至于要不要发展成为男/女友，他们倒是几乎每个人都想过，不是花心，而是天蝎天生爱瞎想，想像一下和某某人如果在一起会怎样对于他们来说是件很有趣的事，但只是想像，很少会主动行动。 ');
INSERT INTO `weibo` VALUES ('48', '一旦天蝎有了男/女友，原本很好的异性朋友关系就变了。天蝎会很有分寸地和他们来往，决不轻易越限。相反，如果天蝎的异性朋友有了他们的男/女友，天蝎一样会保持距离的和好友们来往。，天蝎们真诚地希望朋友能得到自己的幸福。');
INSERT INTO `weibo` VALUES ('49', '恋人之间在要分手的那段时间，经常会打电话不接发短信不回之类的。天蝎对于这样一种状况是非常恼怒的。他们认为就算要分开恋人也犯不着躲着自己。对方越是没反应，天蝎越是说一些恶毒的话来中伤或是讽刺恋人，以此来抒发内心的愤怒。');
INSERT INTO `weibo` VALUES ('50', '在天蝎刚认识一个新的恋人之后，天蝎的行动便开始了。即使发现了对方的有意隐瞒或欺骗，天蝎并不会当时就揭发出来，而是一步步地看着对方露出马脚，不能自圆其说。到那时候，天蝎再冷冷地扬长而去。虽然天蝎也许会有些生气，但因为最终当面揭穿了对方的谎言，那是会让天蝎很有成就感的！在内心永远都会鄙视那个欺骗自己的人。所以，友情提醒一句：千万别骗天蝎，一旦被发现，会面子扫地的。其实天蝎只是很专情， 不许对方骗他们感情而已。 ');
INSERT INTO `weibo` VALUES ('51', '天蝎喜欢占卜，什么星座啦属相啦，他们都比较关心。对于一个刚认识不久的恋人来说，天蝎们会很有兴志地查看关于星座配对啊，其实只是为了想证明一点：自己的选择是正确的，如果碰到说两人不合的情况，天蝎会在心里告诉自己：这都是瞎说的！唉！蝎蝎啊，在这一点上真是有些自欺欺人。 ');
INSERT INTO `weibo` VALUES ('52', '天蝎对于结婚这件事，是有顾虑的。天蝎对恋人的了解是很有趣的。他们有一段时间只对恋人的某一方面进行了解甚至着迷。等过了这段时间，会急着去寻找恋人身上其他的方面，好好珍惜蝎蝎吧，他们的爱大多不掺杂质，纯纯的，傻傻的。 ');
INSERT INTO `weibo` VALUES ('53', '天蝎是害羞的，在公众场合总不太喜欢与恋人有太份亲密的动作，他/她会觉得有失大雅，即使在只有两个人的场合，他们也不太好意思把自己的激情全部释放，因为：蝎蝎们怕自己的热情吓坏了恋人。所以说：蝎蝎还是有顾忌的，远不象网上说的那样我行我素 ');
INSERT INTO `weibo` VALUES ('54', '女蝎蝎理解的世界上的男人应该是个顶天立地、勇敢、讲诚信的硬汉，但也要适时地懂得情调之类。这要求是不是有些高？但往往现实中天蝎没有那么地幸运遇到这样的男人。若遇到了女性化或是做事狭隘的男人，天蝎会把毫不留情地把他看扁的，然后痛骂一顿转身就走。  \n　　相反男蝎对自己的另一半要求是：要有女人味儿，而且越浓越好，这样他们骨子里的那股保护恋人的冲动便有了发挥的空间，男蝎不喜欢女强人或是太过幼稚的女人做他的妻子，他认为一个女人应该是聪明、勤奋温柔且爱家的。 ');
INSERT INTO `weibo` VALUES ('55', '要做好一个天蝎的恋人，还是很不容易的,同理，若你已成为了天蝎的恋人，也证明你非常优秀，至少在天蝎的眼里 ');
INSERT INTO `weibo` VALUES ('56', '天蝎骨子里有伤感的成份，所以在遇到像这样的雨天，他们的心里就会“触景生情”，变得很温柔。实话的说，蝎蝎们平时并不是很柔情，蝎蝎是喜欢浪漫气氛的，当然有他们自己的方式。');
INSERT INTO `weibo` VALUES ('57', '蝎蝎的醋意是蛮足的，所以千万不要在这方面故意挑衅他们的忍受力，他们会很恼火的。如果别的星座有爱吃醋的人的话，那么蝎蝎能算得上是醋厂了，随时随地可能吃醋，即使是恋人有意的一些玩笑也会让他们难过好久的。');
INSERT INTO `weibo` VALUES ('58', '天蝎有时会口是心非，虽然其实星座的人也会这样，但天蝎……是那种不被理解的口是心非型。比如：小时候家人主动要为蝎蝎们买个玩具啊，糖果啊之类的，蝎蝎们明明心里想要，也会嘴上不承认。如果家人明白给他们买了的话，他们会很开心，但如果家人不买了，蝎蝎们又会自己偷偷难过好久。这逻辑是不是很反常啊？这就是蝎子，爱让别人猜心思的蝎子，口是心非！ ');
INSERT INTO `weibo` VALUES ('59', '蝎MM和蝎GG骨子里是争强好胜的，他们总是不服气为什么别人会轻易地超出自己，（尽管有时骑的是自行车！）这一点也很古怪。如果遇到蝎蝎生气的时候，那你就更不要和他们比了，比不过的。而且越是在恋人面前，越是要表现得自己很“强”，哪怕是蝎MM他们自己都说不清楚干嘛要这么做。 ');
INSERT INTO `weibo` VALUES ('60', '蝎蝎的心很软，比如：和恋人闹别扭了，不管是谁的错，只要恋人主动回头只要不是原则上的事，用不了几名“甜言蜜语”蝎蝎就软了，立马和恋人又腻在一起，好像什么都没发生过一样，虽然有时对方并不这么认为。 ');
INSERT INTO `weibo` VALUES ('61', '蝎蝎的耐性是不好的。虽然网上有好多关于蝎蝎坚韧的说话，若是让蝎蝎面对一个又哭又闹的小孩，他们多半是会疯的。刚开始蝎蝎还会相对温和地对待并且不断提醒自己：要温柔要有耐心，若不见效果，那么便会是一顿发作，连吵带打武力解决！ ');
INSERT INTO `weibo` VALUES ('62', '天蝎座其人 \n据说你可以由凝视的眼神认出谁是天蝎座的人。这种眼神高深莫测，明察秋毫，一针见血，然而没有暴露任何东西，即使是仇恨和无情。这一小段描绘，连同这个星座的臭名昭著的本性??激情, 已经够让你的生活难受了。毕竟，当在聚会上的某个人问你是哪个星座的时候，你就会看着他们（目光尖锐地），然后回答说：“天蝎座”。这时他们就会喘口小气然后逐渐后退，或是直接地会问你稍后会做什么。有时候，这会让人感到有一点厌烦。');
INSERT INTO `weibo` VALUES ('63', '天蝎座的人需要经常不断地处于忙碌之中。他喜欢亲自动手去做 \n；喜欢改善自己的工作和生活环境；喜欢更新自己的想法，而不喜欢 \n无所事事和庸庸碌碌的生活，那会使他丧失生机和活力。');
INSERT INTO `weibo` VALUES ('64', '天蝎座的人酷爱权力，喜欢有自己的思想方法。钱和物质对他是 \n不可缺少的，但从不用它来束缚自己的手脚，他对那些对自己的事业 \n、工作有过帮助的人，总是念念不忘，肯为他们慷慨解囊。在生辰天 \n宫图中，当火星在白羊座、天蝎座或摩羯座，或者在黄道第Ⅰ、Ⅹ、 \nⅦ或Ⅳ宫中的影响力较大的时候，这一性格会表现得更为突出。 \n');
INSERT INTO `weibo` VALUES ('65', '天蝎外表总是很冷很酷，第一感觉通常会给人一种斯文/文静而神秘的感觉，会让人有种生人勿近而又想深入了解的矛盾感。如果你能让天蝎御下自身的保护色并成为你的好友。你会发觉天蝎其实心底善良，重感情，易感动，多愁善感，敢爱敢恨！天蝎走的是极端路线，你对他一点好，他将十分回报。');
INSERT INTO `weibo` VALUES ('66', '天蝎座的软肋是看不透,舍不得，输不起，放不下。看不透人际中的纠结，争斗后的隐伤，看不透喧嚣中的平淡,繁华后的宁静；舍不得曾经的精彩，不逮的岁月，舍不得居高时的虚荣，得意处的掌声；输不起一段情感之失，输不起一截人生之败；放不下已经走远的人与事，放不下早已尘封的是与非。');
INSERT INTO `weibo` VALUES ('67', '天蝎座,是好人,是个大大的“滥好人”，心分善恶,情却不分善恶。真心地对待身边的每一人，反被误会周旋于暧昧的境地，博取好感。他们天生有一副好心肠，见不得亲朋受一点苦难；大气豪爽，能力所及的请求会毫不犹豫地答允落实，任劳任怨，那该死的温柔就是学不会拒绝，狠一点，说个“不”。');
INSERT INTO `weibo` VALUES ('68', '\r\n充满神秘色彩的天蝎座是爱憎分明的人，他们不喜欢碌碌无为和无所事事的生活态度，而是喜欢快节奏的生活以及时时更新自己的想法，用自己的双手把周围的环境改变，如果在平静毫无斗志的环境中会让他们感觉到会让自己丧失生机和活力。');
INSERT INTO `weibo` VALUES ('69', '天蝎最害怕爱情的变动，有的天蝎甚至怕到不敢恋爱，害怕激情过去什么都没有。他们的爱情不需要像伏特加一样刺激，也不需要像果汁一样甜蜜，只要如每天饮用的白开水一样就可以。因为白开水每天都会有，味道也永远不会改变，这样的爱情才是天蝎所要的。要征服天蝎只要你能证明会永远对他不离不弃就可以');
INSERT INTO `weibo` VALUES ('70', '\r\n天蝎其实很痛苦。表面上总是很有活力，很快乐的样子，没人时又总是很忧伤。蝎子总会被一种莫名的悲伤笼罩,但不会让别人发现。蝎子很怕被伤害，怕被抛弃,也怕带给别人伤害和不快乐，只能自己硬挺着一切。因为他承受了太多的东西');
INSERT INTO `weibo` VALUES ('71', '天蝎也有辛酸苦楚，不说罢了。天蝎也有执念不放，不说罢了。天蝎也有千回百转，不说罢了。天蝎不是装傻卖乖，不说罢了。不是天蝎未看见，不是天蝎没想过，不是天蝎不懂得，只是不说罢了。');
INSERT INTO `weibo` VALUES ('72', '天蝎座的情感世界：我不敢恭维蝎子的情商，因为你们在爱面前太单纯了~些许有人不信，为什么追不到的那只蝎子可以特别冷漠，其实他对待不爱的人用的是智商，他会理智的去分析得失，但是在真爱面前，他几乎无所保留，即使一无所获，所以感情是蝎子真正的软肋 。');
INSERT INTO `weibo` VALUES ('73', '天蝎有点小闷骚，小寂寞，慢热，从陌生到熟悉需要很长的时间才能交心，害怕冷场，陌生的环境说不到两三句在朋友面前变成话唠。偶尔冷漠，偶尔疯狂。或许有点小叛逆，但是我们都拥有一颗善良的心。不轻易给承诺，但如果说了不管喜恶都尽力去兑现，很难喜欢一个人，认定了就是一辈子。');
INSERT INTO `weibo` VALUES ('74', '天蝎女坚硬的外表下有一颗柔软、需要被精心呵护的心。天蝎女喜静但不高傲，为了爱人她可以包容一切，对她而言，你就是你，独一无二。天蝎的爱是伟大的，因为没有几个星座可以真正做到爱一个人的全部，并且可以为了爱放弃全部！这么忠诚、可靠、对爱人无私奉献的天蝎，谁还怀疑她拥有好命的潜质呢？');
INSERT INTO `weibo` VALUES ('75', '蝎子对好朋友可以很热情，乱七八糟聊个不停；对比较普通的朋友很冷淡，聊不上几句就沉默。蝎子很珍惜对他/她好的朋友，他感觉是坏的，便有意疏离。蝎子的普通朋友很多，好朋友没几个。蝎子很孤独，常常自己一个人。一个人吃饭，一个人上学，一个人逛街，一个人发呆，这就是天蝎，我很好。');
INSERT INTO `weibo` VALUES ('76', '天蝎座很聪明。这种聪明来源于心细，冷静，观察力强。身边的天蝎每到一个环境就会跳脱开来观察每一个人。他们往往能把握住别人的优点、缺点，感情的死穴，然后稳稳下手为他所用。有人说天蝎的人虚伪，其实他们对朋友的好都是真心的，很善良。天蝎做事有魄力，敢作敢当。');
INSERT INTO `weibo` VALUES ('77', '如果你爱天蝎，那么请你原谅天蝎的任性、固执、霸道、冷漠、顽皮、懒惰、偏激、叛逆……天蝎的所有喜怒哀乐都会在爱的人面前表现出来，天蝎并不完美，这样的天蝎你还会爱吗？');
INSERT INTO `weibo` VALUES ('78', '天蝎特点：1脾气来的快去的也快；2有斗志，喜欢拼搏；3刻苦努力，想尽办法独立门户自己当老板，老总最多的星座之一；4重感情，讲义气；5别人对他好，定加倍奉还的典型代表；6不计前嫌，容易哄；7单纯没心机；8喜怒言于表，不伪装；9做事雷厉风行，有效率；10天生的统筹规划专家，计划性强。你中枪了吗');
INSERT INTO `weibo` VALUES ('79', '天蝎座不懂甜言蜜语不屑拍马屁本能的排斥虚伪和做作的人，不会真的发火，就算生气也很快忘记，天蝎座变得冷淡就证明TA开始对你重新审视，当TA越是沉默就代表TA越是生气，天蝎座可能看起来很凶其实内心是最柔软的，看起来很冷淡但那只是保护自己的方法，天蝎座很重视友情 但被伤害后绝对不再友善。');
INSERT INTO `weibo` VALUES ('80', '天蝎很会装，受伤了还装得好像没事一样其实已经心如刀割。不懂他的人会觉得他是开心的，懂他的会看得出他那笑的苦涩痛苦的笑容是假的。天蝎真的很傻，明明就很受伤。天蝎也因为理智所以坚强，他习惯自己疗伤哭自己疗伤，此刻如果没有信得过的人一个肩膀依靠，那只有靠音乐帮自己痊愈。');
INSERT INTO `weibo` VALUES ('81', '有一天，天蝎变得更冷漠，请记得，天蝎曾经真的需要人陪的时候你都只说忙。有一天，天蝎坦然的目中无人了，请记得，曾经是你没有把我好好放在心里。 有一天，天蝎真正不再在乎你了，请记得，曾经你也没有认真听过天蝎的心事。有一天，天蝎不再对你笑了，请记得，你也没有停下来问过天蝎快乐不快乐。');
INSERT INTO `weibo` VALUES ('82', '【天蝎座喜欢一个人的时候，有什么表现？】用小号看他空间，想打电话给对方，又担心会不会引起反感,，找个小事打电话给你，一定要有借口，一本正经的，假装是朋友。天蝎很怕是自己自做多情，如果爱天蝎，一定要大声告诉她(他)~可爱的蝎子是全世界最值得宠爱的星座。');
INSERT INTO `weibo` VALUES ('83', '【让天蝎困惑的8条】 1.无论走到哪都被人称孩子气、傻。 2、有好多事记不住，包括刚刚发生过的事情，一转眼就忘了。 3、刀子嘴，豆腐心。 4、倔强。 5、被人称做没心没肺的人，爱搞笑的人。 6、说话的时候，嘴巴飞快，脑子也快。 7、喜欢玩，从早玩到晚都不会累。8、经常忘记口袋有多少钱。');
INSERT INTO `weibo` VALUES ('84', '【12星座变心时的表现】白羊—变冷淡，金牛—独处时间变多，双子—比较难发现，巨蟹—流露出一点自责，狮子—你怀疑他时惹来一顿骂，处女—常说自己配不上你之类，天秤—粘他时想闪躲，天蝎—擅长瞒天过海，射手—马虎留下的证据，魔羯—异常温柔或不耐烦，水瓶—独自见朋友，双鱼—不知他行踪。');
INSERT INTO `weibo` VALUES ('85', '天蝎座谈恋爱时容易胡思乱想，不能忍受被忽略忽视的感觉，一点点也不能，如果另一半不理TA，TA就会自己胡思乱想一堆，钻进死胡同后出不来。然后另一半一个电话，又瓦解了所有了胡思乱想。想要控制，却又下不了决心。天蝎座表面坚强，内心软弱，想要占有，却又怕太过火，不停地自信与自卑交杂');
INSERT INTO `weibo` VALUES ('86', '天蝎想谈一场长久的恋爱，最好很长很长，最好可以把对方当成像家人一样，每天生活必不可少的人。彼此吵架怎么吵都不会提分手两个字，刚开始可能很热恋，后来可能很平淡也没关系，因为彼此习惯彼此。把对方当成每天生活必然的人，平淡可又不能缺，每天早安晚安，每天醒来都会有彼此的温暖的信息!');
INSERT INTO `weibo` VALUES ('87', '有时候不是不懂，只是不想懂；有时候不是不知道，只是不想说出来；有时候不是不明白，而是明白了也不知道该怎么做，于是就保持了沉默。');
INSERT INTO `weibo` VALUES ('88', '【天蝎座秘密】1不喜欢争吵；2骗我可以，但不要被我知道；3我可以容忍，但别超过我的底线；4我可以装傻，但别以为我真傻；5不喜欢就是不喜欢，说啥也没用；6任何的真话，我都能接受；7对我真心的，我会双倍回报；8爱，最真挚最持久最深沉；9对于装X者，不留脸面。');
INSERT INTO `weibo` VALUES ('89', '天蝎喜欢忙碌而充实的生活，无所事事的日子就是在浪费生命。逃避压力是懦弱的表现。为了自己以后能更加坚强，天蝎会感谢生活中给他带来压力的人。虽然在对抗压力的过程中要遭受很多痛苦和挫折，但是天蝎会笑着去应对，因为蝎子清楚，没有压力的生活会丧失生机和活力。');
INSERT INTO `weibo` VALUES ('90', '如果你的朋友是天蝎座，请好好珍惜！ 天蝎座：体贴第一名，爱吃第一名，爱家第一名，孝顺第一名，多愁善感第一名。如果你爱上天蝎…请你疼爱他多一点，你会得到更多的回报。。。');
INSERT INTO `weibo` VALUES ('91', '如果说到感恩，天蝎是最懂得感恩的星座。天蝎要提防一些伪君子，也就是真小人，通常假装给予自己帮助的人更要多加提防。如果有人总是无条件地帮助天蝎，天蝎可不要傻呼呼地就把对方看成是好人，天蝎放松警惕把自己的秘密全部透露。也许正是这样的好人，会在你最感激她的时候，踩着你的肩膀往上爬。');
INSERT INTO `weibo` VALUES ('92', '【最容易伤到别人的星座排行】第1名：天蝎座；第2名：水瓶座；第3名：天秤座；第4名：处女座；第5名：射手座；第6名：双子座；第7名：魔羯座；第8名：狮子座；第9名：白羊座；第10名：双鱼座；第11名：金牛座；第12名：巨蟹座。');
INSERT INTO `weibo` VALUES ('93', '天蝎座爱一个人总有一个固定的过程，开始表现得很热烈，往后就是平淡，再往后可能看不出来了。很多人会误解你的爱情是图一时新鲜，三分钟热度，其实不然。只是越往后，越深爱，然后就沉默。默默地关心你，默默地对你好……因为天蝎座的爱是经得起沉淀的。');
INSERT INTO `weibo` VALUES ('94', '【天蝎座是什么样的人？】1、天蝎是一个结合温柔与智慧并重非常善良的人。2、天蝎是出产最多好老公好老婆星座的人。3、天蝎是非常爱吃的人。4、天蝎是爱和自己纠结的人。5、天蝎是一个不怎么聪明，但是懂得努力的人。6、天蝎其实就是一个懒人。天蝎座的你，是这样的人吗？？');
INSERT INTO `weibo` VALUES ('95', '喜欢天蝎座一定要很主动很自信才行，不然一定会被天蝎的冷淡吓跑。不过天蝎不喜欢自负的人，不自私，有主见的人是她的最爱。天蝎很能忍，什么事都自己藏在心里不说，所以天蝎的恋人一定要是一个善解人意的人，在天蝎说没关系我很好的时候握住她的手说我知道你不好，陪在她身边。');
INSERT INTO `weibo` VALUES ('96', '【对不起，我是天蝎座】我生气了我会不理你；我伤心了，我会删掉你的一切；我痛苦了，我会毅然的放手。就算心有再多的不甘，我也知道，你已经不属于我，对不起，我的自尊从你那儿收回！');
INSERT INTO `weibo` VALUES ('97', '【12星座花心排行榜】第一名：射手座97分。第二名：双子座95分。第三名：双鱼座94分。第四名：水瓶座90分。第五名：天秤座85分。第六名：白羊座78分。第七名：狮子座69分。第八名：巨蟹座55分。第九名：摩羯座45分。第十名：金牛座43分。第十一名：处女座33分。第十二名：天蝎座33分。');
INSERT INTO `weibo` VALUES ('98', '天蝎座独自一人的时候会迷茫拿著手机不知道做什么。天蝎座和不熟悉的人在一起很斯文不说话会给人很好的感觉但一熟悉起来你会发现天蝎座的单纯和没有长大的心、却又爱玩什麼都敢尝试 天蝎座懒的连下楼买早餐都嫌烦。房间永远乱乱的却给人舒适感。 好好珍惜身边的天蝎座。只因TA们太单纯');
INSERT INTO `weibo` VALUES ('99', '天蝎座的人可以在，很痛的时候说没关系。天蝎可以在，难过的时候说无所谓。天蝎可以在，寂寞的时候哈哈大笑。天蝎可以在，绝望的时候说世界依然美好。天蝎只是希望在，天蝎开始抱怨上天吝啬的时候，有个人可以对天蝎说，别太在意，我心疼你。');
INSERT INTO `weibo` VALUES ('100', '天蝎座总是喜欢故意让别人生气，令人抓狂，这不是心理变态，而是他们觉得会生气说明这是在乎他们。有点傻的可爱的思维方式，他们最怕的不是你们生气，而是你的冷落你的不在乎…没有安全感，占有欲强，控制欲强。爱顾影自怜，N重性格严重精神分裂，特大号神经病。这就是真正的天蝎座！');
INSERT INTO `weibo` VALUES ('101', '【爱上一个人就会无法自拔的星座】冠军（射手座），亚军（处女座），季军（水瓶座），第四名（巨蟹座），第五名（摩羯座）【最讨人喜欢最有人缘的星座】冠军（射手座），亚军（白羊座），季军（水瓶座），第四名（巨蟹座），第五名（狮子座)');
INSERT INTO `weibo` VALUES ('102', '【让天蝎座困惑的8种状况】：1、无论走到哪都被人称孩子气、傻。 2、有好多事记不住，包括刚刚发生过的事情，一转眼就忘了。 3、刀子嘴，豆腐心。 4、倔强。 5、被人称做没心没肺的人，爱搞笑的人。 6、说话的时候，嘴巴飞快，脑子也快。 7、喜欢玩，从早玩到晚都不会累。8、经常忘记口袋有多少钱');
INSERT INTO `weibo` VALUES ('103', '【6月爱情旺、事业旺、财运旺三喜临门星座排行】冠军（射手座）；亚军（天蝎座）；季军（摩羯座）；第四名（巨蟹座）；第五名（处女座）；第六名（水瓶座）；第七名（双鱼座）；第八名（白羊座）；第九名（狮子座）；第十名（天秤座）；第十一名（金牛座）；第十二名（双子座）。你准备好了吗？');
INSERT INTO `weibo` VALUES ('104', '可不可以不要欺骗天蝎？天蝎很容易相信别人，特别是在乎的人，如果你不能保证你能给天蝎实在的，请不要轻易对天蝎许下承诺，不要在答应要买糖给天蝎吃之后却一直都没动作，天蝎虽然表面不会说什么，但其实他们会很受伤，他们只是不想说出来让你愧疚罢了。');
INSERT INTO `weibo` VALUES ('105', '【十二星座谁最容易变心】冠军（射手 97分）、亚军（双子 95分）、季军（双鱼 94分）、第四名（水瓶 90分）、第五名（天秤 85分）、第六名（白羊 78分）、第七名（狮子 69分）、第八名（巨蟹 55分）、第九名（摩羯 45分）、第十名（金牛 43分）、第十一名（处女 33分）、第十二名（天蝎 33分）');
INSERT INTO `weibo` VALUES ('106', '【你不知道的天蝎座】 1.常暗恋；2.不自信 讨厌跟人打交道；3.多愁善感 小小事情纠结N久；4.笑起来是个孩子 冷起来是个谜；5.超懒 爱发呆 擅长装傻；6.热心 易被感动；7.爱讲道理；8.常独处；9.自尊心暴强；10.常年宅在家。全中招的天蝎举下爪子。');
INSERT INTO `weibo` VALUES ('107', '【天蝎座】带着魔鬼般的魅力，让你有如被催眠一样被吸引。忽而热情如火，忽而冷漠像冰，如果你跟ta挑起战端，倒霉的准是自己。天蝎不喜欢浮华的爱情，只想平淡地爱，但必须要刻骨铭心。请记住，蝎子不会随便伤人，除非你先招惹他（她）！');
INSERT INTO `weibo` VALUES ('108', '【天蝎座的10大优点】：1脾气来的快去的也快；2有斗志，喜欢拼搏；3刻苦努力，想尽办法独立门户自己当老板；4重感情，讲义气；5别人对他好，定加倍奉还的典型代表；6不计前嫌，容易哄；7单纯没心机；8喜怒言于表，不伪装；9做事雷厉风行，有效率；10天生的统筹规划专家，计划性强。');
INSERT INTO `weibo` VALUES ('109', '【12星座纠结的分手方式】★想分手却又会藕断丝连的星座—巨蟹座、狮子座、天秤座、双鱼座★不爱时很自私无情的星座—双子座、射手座、魔羯座、水瓶座★分手后爱装潇洒，却希望对方永远记住他的星座—白羊座、金牛座、处女座、天蝎座');
INSERT INTO `weibo` VALUES ('110', '【天蝎座的缺点】1、太过好强；2、占有欲过高；3、善妒；4、爱吃醋；5、疑心病重；6、报复心强；7、得理不饶人；8、感情用事；9、明知故犯；10、口是心非；11、爱恨太强烈。蝎子们，你又占几条呢？？？');
INSERT INTO `weibo` VALUES ('111', '【总想干大事的星座】：第一（天蝎）、第二（天秤）、第三（双鱼）、第四（巨蟹）、第五（魔羯） 【最有赚钱头脑的星座】：第一（天秤）、第二（白羊）、第三（巨蟹）、第四（处女）、第五（天蝎） 【最有脾气的星座】：第一（白羊）、第二（双子）、第三（双鱼）、第四（狮子）、第五（巨蟹）');
INSERT INTO `weibo` VALUES ('112', '【天蝎座是什么样的人？】1、天蝎是一个结合温柔与智慧并重非常善良的人。2、天蝎是出产最多好老公好老婆星座的人。3、天蝎是非常爱吃的人。4、天蝎是爱和自己纠结的人。5、天蝎是一个不怎么聪明，但是懂得努力的人。6、天蝎其实就是一个懒人。天蝎座的你，是这样的人吗？');
INSERT INTO `weibo` VALUES ('113', '【最大度的星座排行】 冠军(射手座)、亚军(水瓶座)、季军(魔羯座)、第4名(狮子座)、第5名(白羊座)、第6名(双鱼座)、第7名(天蝎座)、第8名(巨蟹座)、第9名(金牛座)、第10名(天秤座)、第11名(双子座)、第12名(处女座)。(你是最大度的星座宝宝么？)');
INSERT INTO `weibo` VALUES ('114', '【天蝎座性格特质】1 人前温柔可爱，人后嚣张古怪。2 感情被动，难以把握时机，容易与真爱擦肩而过。3 为人随和，有时会被人认作好欺负。4 爱睡觉、常熬夜、喜欢吃、脾气倔。5 反应慢，巨能忍，长纠结。6 渴望自由，却又喜欢被人约束。7 毅力较好，不用人督促。8 遇事不冷静，容易急躁。对吗？');
INSERT INTO `weibo` VALUES ('115', '【12星座被什么打败】魔蝎座：谎言。水瓶座：背叛。双鱼座：怀疑。白羊座：复杂。金牛座：美食。双子座：寂寞。巨蟹座：冷落。狮子座：自尊。处女座：现实。天秤座：对比。天蝎座：失去。射手座：拘束。');
INSERT INTO `weibo` VALUES ('116', '对待感情，天蝎是个不折不扣的专情星座，他们的感情浓浓的直到内心的最深处，在他们看来，爱情就应该是两厢情愿，容不下任何杂质的，一旦出现背叛或是侵略，哪怕是一点点，他们也不能忍受，感情就只有两种，不是爱就是恨，既然选择转身，就不会回头。你是这样么？');
INSERT INTO `weibo` VALUES ('117', '【12星老公怎样爱老婆】★白羊-为你煮夜宵★金牛-给你实质照顾和承诺★双子-爱屋及乌★巨蟹-要你辞职让他养★狮子-为你离开父母出去住★处女-房子登记你名下★天秤-让你享福当少奶奶★天蝎-天天接送黏着你★射手-愿意陪你回娘家★魔羯-任你使唤当佣人★水瓶-你越来越胖也不离弃★双鱼-钱跟人都交给你');
INSERT INTO `weibo` VALUES ('118', '你没有看到过天蝎座的眼泪，是因为他从来不会在人面前哭，除非你真的把他们的真心夺走了。和天蝎座在一起会感到很随和，因为他会包容你的一切。对于天蝎座真正喜欢的东西，它是会执着的让人害怕的。天蝎座的人不会放弃世界，却会放弃自己，去成全别人，他们懂得原谅和理解。');
INSERT INTO `weibo` VALUES ('119', '【12星座适合培养啥兴趣爱好】白羊座（冒险）；金牛座（艺术）；双子座（各类收集）；巨蟹座（插花）；狮子座（乐队）；处女座（写作）；天秤座（绘画）；天蝎座（旅游）；射手座（摄影）；摩羯座（园艺）；水瓶座（饲养小动物）；双鱼座（瑜伽）你爱好什么？');
INSERT INTO `weibo` VALUES ('120', '其实,天蝎很累了。天蝎习惯假装开心、假装难过，假装在意、假装无所谓,习惯了一个人面对所有。天蝎可以在,很痛的时候说没关系。可以在，难过的时候说无所谓。可以在，寂寞的时候哈哈大笑。可以在，绝望的时候说世界依然美好。天蝎希望在，开始抱怨上天的吝啬时，有个人可以对自己说，我心疼你。');
INSERT INTO `weibo` VALUES ('121', '【12星座MM的弱点】白羊(可爱却没什么气质)、金牛(文静但呆滞)、双子(灵活但聒噪了些)、巨蟹(温柔但喜怒无常)、狮子座(抢眼太霸道了)、处女(聪明却罗嗦到不行)、天秤(有气质却很三八)、天蝎(神秘却冷得像座冰山)、射手(率性但根本就是个男人婆)、摩羯(冷场)、水瓶(怪胎一个)、双鱼(温柔却心机太重)。');
INSERT INTO `weibo` VALUES ('122', '其实无人可以治得住天蝎！如果天蝎座肯让你治，不是真的怕你，而是珍惜你！如果一切觉得没意思的时候，拍拍屁股就走.瞄也不瞄你一眼。你怎样对待天蝎，他就怎样对待你,如果你对天蝎好，天蝎座就会掏十个心对待你。如果你做出一点欺骗背叛天蝎座的事情。天蝎座一定会痛恨你一辈子。');
INSERT INTO `weibo` VALUES ('123', '【12星座男女蜜恋期】白羊座：三个月；金牛座：三年；双子座：忽然间；巨蟹座：整个青春期；狮子座：一年；处女座：一分钟或者一生；天秤座：两年；天蝎座：半年或半生；射手座：一星期；摩羯座：半年；水瓶座：不定时；双鱼座：永远');
INSERT INTO `weibo` VALUES ('124', '其实一个人的时候真的很自由，无拘无束，随心所欲。只是一个人久了，都不知道自己到底要的是什么了，不是没有人追，也不是不想爱。只是不习惯去过两个人的生活，或许还是因为没有遇到那个可以让天蝎心动的人。----- 也许，天蝎的固执，注定了天蝎要单身很久很久。');
INSERT INTO `weibo` VALUES ('125', '【你要改掉什么坏毛病 才能桃花朵朵开】白羊（不发脾气）、金牛（多花钱）、双子（去看演唱会）、巨蟹（当妈）、狮子（养猫）、处女（少说话）、天秤（不犹豫）、天蝎（多睡觉）、射手（严肃）、魔羯（不说谎）、水瓶（减肥）、双鱼（多唱歌）');
INSERT INTO `weibo` VALUES ('126', '如果天蝎主动找你，那是因为你在他心里很重要。如果天蝎不主动找你，那是因为他不知道在你心里，他是否重要。。其实，真爱一个人，天蝎会陷入情不自禁的旋涡中。你让他流泪，让他失望，尽管这样，你站在那里，天蝎还是会走过去牵你的手，不由自主。');
INSERT INTO `weibo` VALUES ('127', '【你的星座上当指数排名第几？】冠军（双子座）、亚军（射手座）、季军（巨蟹座）、第四名（白羊座）、第五名（双鱼座）、第六名（水瓶座）、第七名（金牛座）、第八名（天秤座）、第九名（狮子座）、第十名（处女座）、第十一名（摩羯座）、第十二名（天蝎座）');
INSERT INTO `weibo` VALUES ('128', '如果蝎子喜欢你，他就会喜欢跟你在一起的时候，巴不得天天在一起（起初的时候，如果有工作原因啊什么的就另外了），因为蝎子的全心全意付出，所以他会希望对方也能像自己爱她一样爱自己，如果对方的行为举止让蝎子感到她没这么爱自己的话，他就会难过了，接着忽冷忽热…果然…爱情是天蝎致命伤！');
INSERT INTO `weibo` VALUES ('129', '【十二星座正在想什么？】白羊座：工资又花光了。金牛座：赚大钱。双子座：鸭梨很大。巨蟹座：发奋图强。狮子座：赚大钱。处女座：高铁。天秤座：悠闲的生活。天蝎座：找一份好工作。射手座：赚大钱。摩羯座：发财。水瓶座：睡觉。双鱼座：明天怎么玩。');
INSERT INTO `weibo` VALUES ('130', '天蝎对于朋友，重质不重量，高度要求知心。宁可孤独，也不违心。对于爱情，宁缺毋滥。宁可抱憾终生，也不苟且凑合。风流不羁的言行下，执着追求一种宗教意识的爱情信仰。内心具有高度责任性，忠诚性，自律性以及矛盾性。浪漫儒雅，风趣超脱。拥有奇异诱人的容貌气质。');
INSERT INTO `weibo` VALUES ('131', '【12星座最具有素质及修养排行榜】：冠军（水瓶座）、亚军（天蝎座）、季军（狮子座）、第四名（处女座）、第五名（金牛座）、第六名（射手座）、第七名（双子座）、第八名（双鱼座）、第九名（白羊座）、第十名（天秤座）、第十一名（巨蟹座）、第十二名（摩羯座）');
INSERT INTO `weibo` VALUES ('132', '天蝎看起来是冷漠，在生人面前很文静不爱说话， 但是在朋友面前却十分疯癫。 天蝎的心里都很孤独，他们很需要别人的关怀他们很敏感， 生怕一不小心便被别人忽略 抛弃。 蝎子都是刀子嘴豆腐心，只是生气几天就没事，但就是放不下面子去找你。 所以，请给身边的蝎子多一些温暖吧。');
INSERT INTO `weibo` VALUES ('133', '【12星座生气时变成啥动物】白羊座：蜜蜂；金牛座：屎壳郎；双子座：黑乌鸦；巨蟹座：刺猬；狮子座：老虎；处女座：蚊子；天秤座：南极企鹅；天蝎座：狼 ；射手座：公牛；摩羯座：蜗牛；水瓶座：蛇；双鱼座：小猫。你变成啥动物了？');
INSERT INTO `weibo` VALUES ('134', '【12星座无法假装什么】★白羊—假装冷静★金牛—假装喜欢★双子—假装忘记★巨蟹—假装洒脱★狮子—假装寂寞★处女—假装糊涂★天秤—假装无所谓★天蝎—假装幸福★射手—假装严肃★魔羯—假装快乐★水瓶—假装接受★双鱼—假装坚强');
INSERT INTO `weibo` VALUES ('135', '天蝎女神秘诡谲、令人费解，这也是令人着迷的优点之一。毕竟，有秘密的女人是妩媚动人的。她们被称为“谜一样的女子”：表面看起来很冷漠，甚至是无情的;其实，内心却像是一团熊熊燃烧的火焰。只有真正走进天蝎女的内心，你才会彻底地为她折服。正是这种无法解释的独特魅力，令男子欲罢不能。');
INSERT INTO `weibo` VALUES ('136', '【十二星座最好的妻子排名】冠军（天秤座）、亚军（金牛座）、（巨蟹座）、第四名（狮子座）、第五名（处女座）、第六名（天蝎座）、第七名（射手座）、第八名（摩羯座）、第九名（水瓶座）、第十名（双鱼座）、第十一名（双子座）、第十二名（白羊座)。');
INSERT INTO `weibo` VALUES ('137', '天蝎喜欢独自思考，喜欢把事情考虑的面面俱到，总是喜欢显得自己颇有城府，但是天蝎却是最简单的人，天蝎的世界是二元的世界，所有的人只分成认识的人和不认识的人，认识的人只分成爱的人和恨的人，天蝎的爱与恨都是极端的强烈，爱就爱得刻骨铭心，恨就恨得销魂蚀髓。');
INSERT INTO `weibo` VALUES ('138', '【谁是十二星座该爱的人】白羊（摩羯、巨蟹）、金牛（双鱼、天蝎）、双子（处女、天蝎）、巨蟹（双子、白羊）、狮子（射手、狮子）、处女（金牛、射手）、天秤（巨蟹、金牛）、天蝎（水瓶、双鱼）、射手（巨蟹、金牛）、水瓶（水瓶、处女）、双鱼（处女、天秤）。');
INSERT INTO `weibo` VALUES ('139', '天蝎座吃醋时不爱说话，也不会明讲。 只是你会发现天蝎座有点气嘟嘟的一个人生闷气， 说话语气有点阴阳怪调， 自然就不会给你好脸色看了。 很少说承诺，一旦说出就会履行； 很少说“我爱你”， 说了出来就是真的爱你。');
INSERT INTO `weibo` VALUES ('140', '天蝎座的世界充满着秘密，外人很难探个究竟，有沉着的洞察力和谨慎的行动能力，但不易为人察觉，它深藏在内心深处。天蝎座不善于交际，少言寡语，表达谦虚，容易被他人评价过低，但一旦予以反击，力量足以使对方胆寒。天蝎座总是给人以谦虚感和尊严感。是十二星座中最欢迎也是让大家最咬牙切齿的星座');
INSERT INTO `weibo` VALUES ('141', '【十二星座把你的房子盖在哪最有情致】水瓶座（绝情谷）、双鱼座（峨眉山）、白羊座（黑木崖）、金牛座（武当山）、双子座（桃花岛）、巨蟹座（百花谷）、狮子座（光明顶）、处女座（活死人墓）、天秤座（缥缈峰）、天蝎座（曼陀山庄）、射手座（燕子坞）、摩羯座（白驼山）。');
INSERT INTO `weibo` VALUES ('142', '天蝎座独自一人的时候会迷茫拿著手机不知道做什么。天蝎座和不熟悉的人在一起很斯文不说话会给人很好的感觉但一熟悉起来你会发现天蝎座的单纯和没有长大的心、却又爱玩什麼都敢尝试 天蝎座懒的连下楼买早餐都嫌烦。房间永远乱乱的却给人舒适感。 好好珍惜身边的天蝎座。只因TA们太单纯。');
INSERT INTO `weibo` VALUES ('143', '【最怕生小孩的胆小星座女】金牛座社会环境太差。处女座怕痛。天秤座怕影响性生活。天蝎座不想失去自由身。魔羯座自己都不够花。【十二星座中恋爱只为新鲜的】第一名：双子座。第二名：水瓶座。第三名：双鱼座。第四名：白羊座。第五名：天蝎座。');
INSERT INTO `weibo` VALUES ('144', '天蝎座对待爱情本身就是很专一，在爱情的世界里虽然占有欲太强，但他们对爱情是非常的执着的，当初恋爱的时候，他就会问爱人时间久了，你会厌倦到天天看我吗？所以天蝎座是时间越久他就越爱你，而且他们经受得住外在的诱惑，所以放心的把自己交给天蝎座吧！天蝎座时间越久，爱得越深！蝎子转发吧~');
INSERT INTO `weibo` VALUES ('145', '【12星男最不能忍的女人身材】第五名：排骨精（魔羯座、双鱼座）、第四名：大胸（双子座、狮子座、天蝎座）、第三名：平胸（白羊座、金牛座）、第二名：全身肥胖（巨蟹座、天秤座、水瓶座）、第一名：屁股大腿粗下盘太稳（处女座、射手座）');
INSERT INTO `weibo` VALUES ('146', '12星座女梦想的结婚地是哪？白羊：蔚蓝的空中；金牛：美丽的岛屿；双子：迪士尼乐园；巨蟹：任何方便家族聚会的地方；狮子：广阔的海滩；处女：露天的草坪；天秤：豪华的游轮；天蝎：浪漫的旅行；射手：神秘的海底；摩羯：传统的酒店；水瓶：葡萄酒庄园；双鱼：庄严的教堂');
INSERT INTO `weibo` VALUES ('147', '天蝎座所谓的忽冷忽热，其实是没安全感的体现！有时候你的行为啊话啊触到他敏感的神经后，他就会开始发神经叻!此时，他就会故意远离你，冷淡你，想看你反应！如果你没任何反应，他就开始沮丧了,感觉在独角戏,但如果你对于他的冷表现出热的话,他内心那个激动啊,表面还是风平浪静的。');
INSERT INTO `weibo` VALUES ('148', '天蝎座重视信诺，当你答应她们的事如果没做到，她们会很难过。即使在你许诺的那一天，告诉她们你们有事情或怎么样，她们都会接受这个事实，并安慰自己，但是请你不要欺骗她们，否则你在她心目中的地位会瞬间滑落。');
INSERT INTO `weibo` VALUES ('149', '【爱上那个星座会幸福到爆】冠军（射手座）；亚军（水瓶座）；季军（魔羯座）；第四名（处女座）；第五名（巨蟹座）；第六名（天蝎座）；第七名（金牛座）；第八名（双鱼座）；第九名（天秤座）；第十名（双子座）；第十一名（狮子座）；第十二名（白羊座）~你是幸福的人儿吗~?');
INSERT INTO `weibo` VALUES ('150', '蝎子不轻易付出真感情，要不是真正的爱，是不会说“我爱你”这三个字的。可以喜欢很多人，但爱的人只有唯一的那个，而且还死心眼，不听旁人的劝阻。选定了，撞了南墙还不死心，是个痴情的种。');
INSERT INTO `weibo` VALUES ('151', '【12星座永不变的性格】白羊座（坦白率真）、金牛座（脚踏实地）、双子座（足智多谋）、巨蟹座（亲切温暖）、狮子座（热情开朗）、处女座（勤奋努力）、天秤座（能屈能伸）、天蝎座（深谋远虑）、射手座（正直坦率）、摩羯座（谨慎谦逊）、水瓶座（创意十足）、双鱼座（善解人意）');
INSERT INTO `weibo` VALUES ('152', '天蝎座的人不会放弃世界，却会放弃自己去成全别人，他们懂得原谅和理解，无论这一秒他有多讨厌一个人，下一秒看到那个人脆弱的一面，他还是会去无条件地帮助他，真的很傻吧？但是傻的好让人心疼。他们的执着只是针对自己的，宁愿孤独的面对一切，因为不知道怎么表达自己的内心，所以他们选择了沉默。');
INSERT INTO `weibo` VALUES ('153', '【星座女孩好色基因】白羊（魅惑高手）；金牛（比较闭俗）；双子（标准的表里不一）；巨蟹（隐形好色基因）；狮子（纯真与激情的综合）；处女（饿鬼假小心）；天秤（恋爱狂烧很豪放）；天蝎（为爱疯狂）；射手（通常只想想）；摩羯（保守闷出病）；水瓶（亲亲摸摸表心意）；双鱼（高级班好色女）');
INSERT INTO `weibo` VALUES ('154', '天蝎过于孩子气，可爱是可爱，但有时候未免显得有点儿没担当；天蝎非常爱玩，精力充沛，跟不上他步伐的还是算了吧；天蝎热情有限，QQ上非常不爱主动找人聊天，除非是关系特别铁的朋友；天蝎脾气有点儿火爆，但基本属于气来得快去得也快型，不难哄，只是不喜欢主动拉下面子哄人，宁愿跟你冷战。');
INSERT INTO `weibo` VALUES ('155', '【6月艳遇指数最高的12星座排行】第一名：天蝎座。第二名：射手座。第三名：天秤座。第四名：金牛座。第五名：水瓶座。第六名：巨蟹座。第七名：双鱼座。第八名：狮子座。第九名：白羊座。第十名：双子座。第十一名：处女座。第十二名：摩羯座。好期待有木有！！');
INSERT INTO `weibo` VALUES ('156', '天蝎座特别大方，特别无私，朋友有难，二话不说，尽自己的能力能帮则帮。但骨子里很有自尊，一般不轻易求别人帮助，除非是和自己关系好到不行的朋友。如果开口求人帮助，别人犹豫那么几分钟，天蝎立刻会收回自己的要求，以后再也不会请求他帮忙。');
INSERT INTO `weibo` VALUES ('157', '【吸金能力比老公强的星座】冠军（巨蟹座）、亚军（处女座）、季军（摩羯座）、第四名（白羊座）、第五名（天蝎座）；【最善于守财的星座】冠军（处女座）、亚军（天蝎座）、季军（巨蟹座）、第四名（金牛座）、第五名（摩羯座）。');
INSERT INTO `weibo` VALUES ('158', '天蝎座在等一个人，一个可以把天蝎座的寂寞故事画上休止符的人；一个可以陪天蝎座听遍所有悲伤情歌，却不会让天蝎座想哭的人；一个天蝎座可以在他身上找出一百个缺点，却还是执意要爱他的人；其实，天蝎座一直都在等你，希望你能知道。');
INSERT INTO `weibo` VALUES ('159', '天蝎座外表温和，偶尔孩子气，内心有狂野的一面，喜欢旅游但也恋家，不算太宅。容易陷入自己的想象世界不能自拔。高度的细腻敏感（对于自己在意的东西），高度的冷漠绝情（对于不入眼的东西），情感强烈而绵长，习惯虐人虐己。对待回忆郑重而感性，无比怀旧，自我保护意识强。');
INSERT INTO `weibo` VALUES ('160', '【十二星座如何对待旧情人】白羊座（冷淡）；金牛座（自责）；双子座（无所谓）；巨蟹座（思念）；狮子座（居高临下、伺机报复）；处女座（冷静）；天秤座（徘徊）；天蝎座（仇恨）；射手座（决不回头）；摩羯座（耐心等待）；水瓶座（喜新不厌旧）；双鱼座（藕断丝连）。');
INSERT INTO `weibo` VALUES ('161', '【天蝎座喜欢的安静的方式】1.坐在沙滩上看大海 吹海风；2.在雨中漫步 不打伞；3.在博客或其他玩的网站写自己的心情；4.以各种方式发呆；5.一个人塞着耳机漫步；6.看着书 听着歌；7.脑袋一片空白 什么都不想；8.和恋人背靠着背坐在一起 不说话；9.托着腮帮想心事；10.一个人听着歌 喝点酒。');
INSERT INTO `weibo` VALUES ('162', '【感情最专一的12星座排名】 第一名： 天蝎座；第二名： 摩羯座：第三名：金牛座；第四名：处女座；第五名：巨蟹座；第六名：双鱼座；第七名：狮子座；第八名：白羊座；第九名：水瓶座；第十名：射手座；第十一名：天枰座；第十二名：双子座。');
INSERT INTO `weibo` VALUES ('163', '如果天蝎座喜欢你，他就会喜欢跟你在一起的时候，巴不得天天在一起（起初的时候，如果有工作原因啊什么的就另外了），因为蝎子的全心全意付出，所以他会希望对方也能像自己爱她一样爱自己，如果对方的行为举止让蝎子感到她没这么爱自己的话，他就会难过了，接着忽冷忽热…爱情，是天蝎致命伤！');
INSERT INTO `weibo` VALUES ('164', '【有关于十二星座的寓言故事】白羊（两只口袋）；金牛（寡妇与母鸡）；双子（马与马夫）；巨蟹（蚂蚁与推粪虫）；狮子（徒劳的寒鸦）；处女（山震）；天秤（狐狸和葡萄）；天蝎（小男孩与蝎子）；射手（老猎狗）；摩羯（站在屋顶的小山羊与狼）；水瓶（公鸡和宝玉）；双鱼（狼与鹭鸶）。');
INSERT INTO `weibo` VALUES ('165', '【12星座结婚坐什么车最适合】天蝎座（兰博基尼）；白羊座（奔驰）；金牛座（红旗）；双子座（保时捷）；巨蟹座（法拉利）；狮子座（吉利）；处女座（玛莎拉蒂）；天秤座（凯迪拉克）；射手座（斯大林格勒拖拉机厂生产的-t34拖拉机）；摩羯座（马自达）；水瓶座（奥迪）；双鱼座（宾利）');
INSERT INTO `weibo` VALUES ('166', '【命中注定要在一起的星座】（白羊、射手）、（金牛、处女）、（双子、天秤）、（巨蟹、天蝎）、（狮子、白羊）、（处女、摩羯）、（天秤、水瓶）、（天蝎、双鱼）、（射手、狮子）、（摩羯、金牛）、（水瓶、双子）、（双鱼、巨蟹）。');
INSERT INTO `weibo` VALUES ('167', '虽说天蝎不会主动参与到矛盾的是是非非中去，但如果纷扰主动找上他们，潜在的火爆脾气肯定会惊到你。天蝎本身就特别反感别人对自己说三道四，不管有没有道理，都难以接受当面的指责。在他们看来，这和侮辱的差别，也就是五十步笑百步。挑衅的眼神望着对方，甚至会在气头上说一些很极端的话。');
INSERT INTO `weibo` VALUES ('168', '残月暮色，独舞晚风，陌上红尘，桃花败落，凋零花瓣，随风而碎，指尖染殇，渲红墨笔，红颜如梦，花堪折，黯然一世风华。浮生若梦，烟花易冷，梦呓易坠，几时共舞。浮生未醉，挥斩一世情殇，三生弱水畔，凝眸遥望，轮回边缘。笑问谁是摆渡人，醉语何年缘再续，叹息红尘情何物');
INSERT INTO `weibo` VALUES ('169', '其实什么都懂，只是不愿意揭穿它。不想碰它，更不想蹲下来去整理它。提及也好，携带也罢，都终是一场说到重点的故事。可以拼了命的努力得到这份需要，但还是坚持的说要放弃。而我一直想做一个有自知之明的女人，那样总可以面对着镜子整理自己。告诉自己不是不爱。');
INSERT INTO `weibo` VALUES ('170', '\r\n就这样，你离开了。你永远也不会明白，最难熬的日子我如何熬过；永远也不会明白，最炙热的感情我如何熄灭；永远也不会明白，最苦涩的伤口我如何掩埋；永远也不会明白，最空虚的孤独我如何用血与泪一点点地填满。相遇了，冷淡了，放弃了，没有结局的爱，总有人先离开，所以我又何德何能，奢求你明白。');
INSERT INTO `weibo` VALUES ('171', '\r\n别问我是否还是朋友，那些美好或伤心的过往，在分手一刻就碎了一地，拼不回昨天，也撑不起友情的明天。别再试探你在我心中的位置，你见过我爱得最傻的模样，是谁怎样不留后路，彼年豆蔻，谁许谁地老天荒。别祝我幸福，向来缘浅，奈何情深，要有多坚强，才敢念念不忘...童话已经结束，遗忘就是幸福。');
INSERT INTO `weibo` VALUES ('172', '不要用女朋友的数量来显示你的魅力。如果你爱一个人，请你温柔的呵护她；如果不爱，请直说，不要敷衍她。你工作再忙，也要记得打个电话给你心爱的人，因为她在等待，请不要让她失望。不要认为每个女子都爱钱如命，你赚钱很辛苦。但这个世界上能养活自己的女人比比皆是。');
INSERT INTO `weibo` VALUES ('173', '\r\n男人该要记住：1.伤什么都别伤心爱人的心。2.打什么都别打女人。3.有了矛盾，立刻解决。4.学会帮女人做家务。5.如果你爱一个人，请你温柔的呵护她；如果不爱，直说。6.想她的时候，告诉她。7.不要认为每个女子都爱钱如命。8.牵她的手漫步。不是为了让别人看，是要两个人感觉幸福。9.偶尔给对方惊喜');
INSERT INTO `weibo` VALUES ('174', '你若深爱一个人，就要学会阻止自己，不要把他当成全部，不要所有的话都跟他讲，不要所有的秘密都和他分享。你投入的多了，你就会慢慢地忘记了自己，没有自我的人，在爱情里是找不到自己的位置。唯一的结局，爱情被你抓得越紧，却逃得越远，最终只能击碎你的梦幻，让曾经的诺言，如飞花般吹散在风中。');
INSERT INTO `weibo` VALUES ('175', '【转给我爱的人】1、即使全世界都背叛你，我也会站在你身边背叛全世界。2、我不怕下地狱，我怕的是地狱里....没有你。3、我教会自己喜欢的人学会如何去爱，只可惜……他爱的那个人不是我。4、只要你要，只要我有。5、只要你为我流一滴眼泪,我就可以为你活下去。6、我颠覆了整个世界,只为摆正你的倒影。');
INSERT INTO `weibo` VALUES ('176', '有的时候你的梦想太大，别人说你的梦想根本不可能实现；有的时候你的梦想又太小，又有人说你胸无大志；不过又能怎么样呢，未来始终是自己的，梦想始终是自己的，没有人会来帮你实现它。这个世界上没有不带伤的人，真正能治愈自己的，只有自己。——《你要去相信，没有到不了的明天》');
INSERT INTO `weibo` VALUES ('177', '\r\n有些人闯进你的生活，只是为了给你上一课，然后转身离开。不是每个人都适合与你白头到老。有的人，是拿来帮你成长的；有的人，是拿来一起生活的；有的人，是拿来一辈子怀念的。无论生活得多么艰难，最后你总会找到一个让你心甘情愿傻傻相伴的人……');
INSERT INTO `weibo` VALUES ('178', '你生来是怎样的人，就注定了是怎样的人，无论你多么羡慕另外一种人生，但那不是你的，就不是你的。哭闹没有用，忌妒没用，甚至拼命地改造自己都没有用。我们始终只能按照自己内心最认同的那种方式生活，所以，你想要怎样的人生，就会获得一个怎样的人生，这句话，是真的……');
INSERT INTO `weibo` VALUES ('179', '【10个破坏爱情的小细节！】1、总是想赢；2、不信任；3、不交流；4、不倾听；5、花钱不节制；6、怕分手；7、太依赖；8、期望得到快乐；9、从不争执；10、想得简单或者想得太难。');
INSERT INTO `weibo` VALUES ('180', '【女孩，一定要记住的话！】1．不要再相信这个世界上会有纯粹的爱情，一个只拥有爱情的女人是不会幸福的。2．以婚姻为目的的恋爱，应该是理智的而不仅仅是浪漫，要充分考虑到对方的学识，家境，嗜好以及秉性。3．随缘，但不是说不努力。4．永远不要问这个问题：“为什么不爱我”。');
INSERT INTO `weibo` VALUES ('181', '\r\nImmature love says: “I love you because I need you.” Mature love says: “I need you because I love you .”——不成熟的爱说：\"我爱你因为我需要你。\" 而成熟的爱说：\"我需要你因为我爱你。');
INSERT INTO `weibo` VALUES ('182', '\r\n很多人，因为寂寞而错爱了一个,但更多的人，因为错爱一个人，而寂寞一生。我们可以彼此相爱，却注定了无法相守。不是我不够爱你，只是我不敢肯定，这爱，是不是最正确的。');
INSERT INTO `weibo` VALUES ('183', '你知道不知道,思念一个人的滋味,手机总是拿在手里，一遍又一遍地拨着那几个数字,却永远没有勇气拨出去;你知道不知道,思念一个人的滋味,是当电话响起时,会心慌意乱,看见来电显示时,却是沉沉地失落；你知道不知道,思念一个人的滋味,总是呆坐在电脑前,对着屏幕发呆，脑海里却时刻想着你....');
INSERT INTO `weibo` VALUES ('184', '你是否经常狠不下心来做事，对自己不够狠，对别人也不够狠。所以，你总是黏黏糊糊，总是不忍心去拒绝别人，总是下不了决心让自己过的更好，总是缠绵过往不能自拔……优柔寡断的你，必须狠一次，否则你永远也活不出自己。');
INSERT INTO `weibo` VALUES ('185', '我们已经多久不联系了。感觉这一辈子都不会再见到你了。有些事，不说是个结，说了就是一个疤。那些不能说的秘密，会不会成为我们永不见面的借口。一直在想，很多年以后，如果我和你，就这样再也不联系，可突然有一天，就这么站在喧嚣的人群里，相互注视着对方，第一句话需要多大的勇气才说的出。');
INSERT INTO `weibo` VALUES ('186', '世上没有不伤人心的感情，或多或少，或大或小，它都会在你的灵魂上留下伤痕的，以伤痕为代价换得感情的喜悦，以感情的喜悦作为回报的伤痕。这世界上，没有能回去的感情。就算真的回去了，你也会发现，一切已经面目全非。唯一能回去的，只是存于心底的记忆。是的，回不去了，所以，我们只能一直往前……');
INSERT INTO `weibo` VALUES ('187', '男人如果注定是你的，你就永远不会失去他，如果他不是你的，不论你用尽千方百计，仍然永远得不到他。当你拥有适当的爱情，遇到适当的男人，你们俩都会在适当的时候知道，彼此是天造地设的一对，会牵手走一生。那个妙不可言的一刻，才是值得等待的，所以逼来的承诺不可靠……');
INSERT INTO `weibo` VALUES ('188', '有些故事，不一定要讲给所有人听；有些悲伤，不一定谁都会懂；有些伤口，时间久了就会慢慢长好；有些委屈，受过了想通了也就释然了；有些伤痛，忍过了疼久了也成习惯了；有些藏在心底的话，不想说也就没必要说了。其实，并不是所有的痛，都可以呐喊；不是所有的爱，都可以表白……');
INSERT INTO `weibo` VALUES ('189', '【只有好朋友才会这么说】1、你怎么这么烦人啊；2、别跟我臭得瑟；3生病了还到处走，想死啊；4、我才懒得管你呢；5、你怎么能跟他在一起；6、你这么做值么；7、你俩不合适只有朋友才会这样说：分了更好，免得你更伤心；8、别在那做梦了；9、有我在，不用怕。—— 你身边有这样的朋友吗？');
INSERT INTO `weibo` VALUES ('190', '喜欢你，却不一定爱你。爱你，就一定很喜欢你。其实，喜欢和爱仅一步之遥。但，想要迈这一步就看你。是喜欢迈这一步，还是爱迈这一步。喜欢很容易转变为爱，但爱过之后却很难再说喜欢。喜欢是轻松而淡淡的心态，爱一旦说出了口，就变成了一种誓言，一种承诺。');
INSERT INTO `weibo` VALUES ('191', '有时候，明明清楚是错误的决定，却还在苦苦坚持，只因永远不肯服输；有时候，明明说着看开了，却总是在微笑沉醉时输给了现实，只因想到了伤痛；有时候，明明知道是没有结果的爱恋，却仍旧不肯放弃，只因心中依然有爱。其实，有时候，放弃，才是真正的开始。');
INSERT INTO `weibo` VALUES ('192', '我想给你幸福，却走不进你的世界。我想用我的全世界来换取一张通往你世界的入场券，不过，那只不过是我的一厢情愿而已。我的世界，你不在乎；你的世界，我被驱逐。我真的喜欢你，闭上眼，以为我能忘记，但流下的眼泪，却没有骗到自己。');
INSERT INTO `weibo` VALUES ('193', '我最爱的，往往没有选择我；最爱我的，往往不是我最爱的；而最长久的，偏偏不是我最爱也不是最爱我的，只是在最适合的时间出现的那个人。如果爱有原因，那就不爱了');
INSERT INTO `weibo` VALUES ('194', '1.所谓夫妻就是相爱一辈子，争吵一辈子，忍耐一辈子。2.所谓花心，就是有了爱情和面包，还想吃蛋糕的心情。3.所谓幸福就是你吃鱼，我吃肉，看着别人啃骨头。4.所谓自恋，就是下辈子我要投胎做男人，然后取个像我这样的女人。5.所谓家就是夫妻共同经营的，编织着梦和苦辣酸甜的窝。');
INSERT INTO `weibo` VALUES ('195', '爱上一个人的7个预兆：1当你在忙时，却把手机开著，等著她/他的短信；2喜欢和她/他单独漫步；3在一起时假装不注意，离开后会急著找她；4当她/他受伤或生病时，会很关心她替她着急；5她/他和别人要好时，你会吃不知其味；6看到她/他甜美的笑时，会扬起得意的笑；7看到这儿，心里想到某个人.');
INSERT INTO `weibo` VALUES ('196', '亲爱的，我已经学会不哭了，我也会在看见阳光灿烂的时候微笑了；亲爱的，我已经学会长大了，我也会在遇到困难的时候自己解决了；亲爱的，我依然爱你，不过，现在我已经学会更爱我自己了。');
INSERT INTO `weibo` VALUES ('197', '让人幸福的事情：有人爱，有事做，有所期待。有人爱，不仅仅是被人爱，而且有主动爱别人爱世界的能力；有事做，让每一天充实，事情没有大小，只有你爱不爱做；有所期待，生活就有希望。人不怕卑微，就怕失去希望，期待明天，期待阳光，人就会从卑微中站起来，带着封存梦想去拥抱蓝天……');
INSERT INTO `weibo` VALUES ('198', '或早或晚，能遇见你就好，或多或少，你在乎我就好，或风或雨，能牵着你就好，或苦或乐，我们在一起就好。亲爱的，愿你因我而幸福。');
INSERT INTO `weibo` VALUES ('199', '男人哭了，是因为他真的爱了；女人哭了，是因为她真得放弃了。能够说出的委屈，便不算委屈；能够抢走的爱人，便不算爱人….');
INSERT INTO `weibo` VALUES ('200', '那时候，喜欢上线喜欢网聊。跟认识的人聊生活，跟不认识的人聊感情。如意的不如意的，什么都可以聊。而现在，跟认识的人很敷衍，要么“呵呵”一笑，要么一连串句号。跟不认识的人，索性不理或假装消失。苦与乐，再不愿说与谁听。开始懂了：谁都不是谁的天使，谁也救赎不了谁！终究，我们只能靠自己。');
INSERT INTO `weibo` VALUES ('201', '天蝎座的人在正常情况说出的话就一定是真的，请相信他们。他们最讨厌别人对他们的话不相信，然后说什么“你是不是这么想的你心里清楚”之类的话……天蝎座的人会觉得特别委屈。要记住社会再黑暗，人们再圆滑，也还是会有一些人保持心中的那一份静土，对别人坦诚的，那就是天蝎座。');
INSERT INTO `weibo` VALUES ('202', '天蝎座拥有的执著是一块顽固坚硬的大石头，任何强大的武器都无法击碎它，就算全世界反对他或她，也不会令其退后一步。能让这块顽强的石头出现缝隙，只需要天蝎座所珍惜人的一滴眼泪，击毁的不仅是本身，更是天蝎内心的整个世界。');
INSERT INTO `weibo` VALUES ('203', '人一辈子一定要有个女儿，从小留着长发，还有刘海儿，给她穿小靴子，春天带她到处玩，给她编花环戴着，夏天给她买冰棍吃，秋天带她走在满是落叶的石板路上，冬天带她打雪仗，逗她气呼呼的说：我不跟你玩了，你是个坏人。上学了给她梳麻花辫子，听她咿呀呀的念课文…最后她嫁人，你哭成泪人儿… ');
INSERT INTO `weibo` VALUES ('204', '\r\n每一个天蝎座都有曾经的纯情史，只是当爱过之后，一旦受伤，他们就会把伤痛放大无限倍，并且冰封自己的心，远离下一次的伤害。 你们是不是这样？？');
INSERT INTO `weibo` VALUES ('205', '\r\n天蝎座爱一首歌，常常是因为某句歌词，但真正动人的不是那句歌词，而是在Ta生命中那些关于这首歌的故事。');
INSERT INTO `weibo` VALUES ('206', '【十二星座，为爱情会流多少次泪？】双子座：（3次） 天秤座：（10次） 金牛座：（6次） 天蝎座：（爱一次哭一次） 射手座：（2次） 水瓶座：（无数次） 双鱼座：（缺爱，无） 白羊座：（20次） 摩羯座：（1次） 巨蟹座：（最多，一直未被超越） 处女座：（9次） 狮子座：（99次）');
INSERT INTO `weibo` VALUES ('207', '天蝎座通常只会能忍则忍，把什么事都放在心里，表面上看，嘻嘻哈哈没怎样，但是心里莫大的委屈就只有自己知道。蝎子们很容易开心也很容易伤心，可又没人知道，Ta们只是习惯了容忍凡事先微笑，可Ta们心里的委屈又有谁愿意为其承担。');
INSERT INTO `weibo` VALUES ('208', '天蝎座拥有的执著是一块顽固坚硬的大石头，任何强大的武器都无法击碎它，就算全世界反对他或她，也不会令其退后一步。能让这块顽强的石头出现缝隙，只需要天蝎座所珍惜人的一滴眼泪，击毁的不仅是本身，更是天蝎内心的整个世界。');
INSERT INTO `weibo` VALUES ('209', '【天蝎座女生全优点】1、天蝎座女生在十二星座中出了名的孝顺；2、对爽约的人很生气；3、会记住爱人生日；4、理想的家庭主妇；5、性格偏于内向；6、向往安稳的生活；7勇敢；8会存钱；如果你决心要娶一个天蝎座的女生回家我会说：哥们，你真的有福了!');
INSERT INTO `weibo` VALUES ('210', '十二星座的不要不要依靠射手、不要爱上天蝎、不要留恋金牛、不要应付处女、不要藐视狮子、不要相信魔羯、不要迁就双子、不要猜测水瓶、不要容忍白羊、不要给双鱼花钱、不要对天平吵闹、不要对巨蟹先动情。');
INSERT INTO `weibo` VALUES ('211', 'Have the person love，I will try to do a lovely man．The sun is bright, the wind and rain，do his own dream run，go his own way．—— 有没有人爱，我也要努力做一个可爱的人。不埋怨谁，不嘲笑谁，也不羡慕谁，阳光下灿烂，风雨中奔跑，做自己的梦，走自己的路.....');
INSERT INTO `weibo` VALUES ('212', '如果你觉得天蝎残酷冷漠，那只是你们还没有了解透彻天蝎，其实天蝎的内心热情。很多人都觉得天蝎是没心没肺的那种，其实只是天蝎把很多事都看的很透。如果天蝎愿意与你倾诉自己心里的想法，愿意为你流泪，为你做傻事，想为你放下面子。那代表你是他爱的人，他会为你奋不顾身。');
INSERT INTO `weibo` VALUES ('213', '天蝎特点：1脾气来的快去的也快；2有斗志，喜欢拼搏；3刻苦努力，想尽办法独立门户自己当老板，老总最多的星座之一；4重感情，讲义气；5别人对他好，定加倍奉还的典型代表；6不计前嫌，容易哄；7单纯没心机；8喜怒言于表，不伪装；9做事雷厉风行，有效率；10天生的统筹规划专家计划性强。你中枪了吗？');
INSERT INTO `weibo` VALUES ('214', '星座之最最帅星座：射手，最美星座：天蝎,最好看的星座：双子、天秤、水瓶，最可爱的星座：双鱼，最活泼星座：白羊、水瓶、射手，最专一的星座：金牛、天蝎、巨蟹，最花心的星座：双子、射手、水瓶，最稳重的星座：摩羯、金牛、天蝎，最浪漫的星座：双鱼、天秤、双子，最木讷的星座：摩羯、金牛');
INSERT INTO `weibo` VALUES ('215', '如果你对天蝎表白后，天蝎对你说“不喜欢你”或类似的话，就等于判了你死刑。这时不要想着继续努力来感动天蝎，没用。天蝎就像弹簧，你施力越大，TA们就把你弹的越远。天蝎对自己不喜欢的人可以很残忍，就算心里会内疚也会继续残忍，这也是天蝎最冷血的时候。如果还想做朋友就什么都不要做。有木有');
INSERT INTO `weibo` VALUES ('216', '我希望你幸福，因为那是我最大的心愿；我又怕你幸福，因为那样你就会忘了我。世界上最动人的情话，不是“我爱你”，而是在我需要的时候，你说“ I’ll be there ” 。一个人爱不爱你，在不在意你，你是感觉得到的。如果，你喜欢的人不喜欢你，那么，就算全世界的人都喜欢你，你还是觉得很孤独吧？');
INSERT INTO `weibo` VALUES ('217', '天蝎座通常只会能忍则忍，把什么事都放在心里，表面上看，嘻嘻哈哈没怎样，但是心里莫大的委屈就只有自己知道。蝎子们很容易开心也很容易伤心，可又没人知道，Ta们只是习惯了容忍凡事先微笑，可Ta们心里的委屈又有谁愿意为其承担');
INSERT INTO `weibo` VALUES ('218', '天蝎与双鱼的相处，可以说是完全上演了电视剧里的爱恨情仇，悲欢离合。天蝎座性情激烈，而双鱼座则温柔腼腆。活得太过梦幻的双鱼，当看到天蝎的干练和冷静，感到天蝎又能够懂得人事和情感，双鱼们便不由自主地会想要把心托付给这样的人。就这样，双鱼会深爱上天蝎而不能自拔了。');
INSERT INTO `weibo` VALUES ('219', '天蝎有时候疯疯癫癫，有时非常严肃，所以根本搞不懂自己想幹嘛 可是 讨厌别人不信任和误会，遇到不开心的事会憋在心里，心底的話 很少跟別人说，不是不想说，而是不知道怎麼開口，就算說了， 別人還是怎麼也不懂自己的想法 天蝎座還是只有天蝎座的人才懂。');
INSERT INTO `weibo` VALUES ('220', '\r\n天蝎座的女生，见一眼，便知道自己喜不喜欢。一个动作，一句话，一个神情，都可能是瞬间吸引她们的东西。同样的，微妙的一点，就可以让她们瞬间对一个人死心。对她们来说，细节真的可以打败爱情。');
INSERT INTO `weibo` VALUES ('221', '越长大，就越习惯压抑内心的真实感受，不再放声大哭放声大笑，什么都只是淡淡的点到为止。好像越来越没有什么事，可以伤心到落泪，再也找不 出，释放伤感的出口。如果有时间有机会自由的哭，总是好的；如果可以狠狠流出眼泪，就说明心没有干涸。现在明明感觉到痛，却再也无法畅快的流泪。');
INSERT INTO `weibo` VALUES ('222', 'The ones you love the most are always the ones who hurts you the most．—— 你最爱的人，往往把你伤得最深……');
INSERT INTO `weibo` VALUES ('223', '学会低调，取舍间，必有得失。做自己的决定，然后准备好承担后果。慎言，独立，学会妥协的同时，也要坚持自己的底线。明白付出并不一定有结果。过去的事情可以不忘记，但一定要放下。要快乐，要坚韧，要温暖，给予真诚。愿我做到这一切，只为久等的旧人……');
INSERT INTO `weibo` VALUES ('224', '我们不要去羡慕别人所拥有的幸福。你以为你没有的，可能在来的路上；你以为她拥有的，可能在去的途中。有的人对你好，是因为你对他好；有的人对你好，是因为懂得你的好！成熟不是心变老，而是眼泪在眼睛里打转，我们却还能保持微笑；总会有一次流泪，让我们瞬间长大。');
INSERT INTO `weibo` VALUES ('225', '第一次哭，是因为你不在；第一次笑，是因为遇到你，第一次笑着流泪，是因为不能拥有你。有时候，爱也是种伤害；残忍的人，选择伤害别人；善良的人，选择伤害自己。');
INSERT INTO `weibo` VALUES ('226', '\r\nIt takes being away from someone for a while，to realize how much you really need them in your life．—— 有的时候，你需要离开某人一段时间，才会发现自己有多需要他……');
INSERT INTO `weibo` VALUES ('227', '【这些小幸福，你拥有吗？】1.爸妈很疼爱你；2.有好事情有人第一个想到你；3.得到过第一名；4.得到过惊喜；5.笑到肚子痛；6.病的时候有人照顾；7.有人为你哭泣；8.和心爱的人一起走路到腿疼；9.半夜有人发短信给你；10.和密友一起煲电话粥。');
INSERT INTO `weibo` VALUES ('228', '找个喜欢和你说话的人，比找个能带给你物质生活的人更重要。遇见那个愿意和你分享所见所闻、和你分析所面对问题的利与弊的人，请珍惜，愿意和你唠叨的人，也许他并没有钱没有权，但他有心……');
INSERT INTO `weibo` VALUES ('229', '请记住，无论什么时候，你都需要给自己一个明确的底线，因为很多时候有些人他会一点一点磨消你的底线，当你没有底线的时候，你就完全被别人控制……');
INSERT INTO `weibo` VALUES ('230', '这些日子，仰望天空，脑海中会浮现许多人的样子。一些人离开，没有归期；一些人离开，永不再会。好像只是我一个人留在原地。等待，或者怀念。怀念离开的人留在掌心的记忆，等待未来的人给我新奇。常常分不清楚，到底是物是人非了，还是人是物非了。');
INSERT INTO `weibo` VALUES ('231', '如果你能解释为什么会喜欢一个人，那么这不是爱情，真正的爱情没有原因，你爱他，不知道为什么。');
INSERT INTO `weibo` VALUES ('232', '我们说过的话，做过的事，走过的路，遇过的人，每一个现在，都是我们以后的回忆。无须缅怀昨天，不必奢望明天，只要认真过好每个今天，说能说的话，做可做的事，走该走的路，见想见的人。脚踏实地，不漠视，不虚度，快乐悲伤都要记得，就算心碎也要拥有最美的姿态。');
INSERT INTO `weibo` VALUES ('233', '有些事情，只有经历了，才有穿透心扉的体验；曾经的人，只有从心底放下，心灵才会真正解脱。没有哪件事，能够一直捆住你的手脚；没有哪个人，能够成为你永远。所以，想做的事，只要有能力做，那就不要等，不要害怕失败；想付出的爱，只要觉得可以，那就大胆些，不要留下遗憾。');
INSERT INTO `weibo` VALUES ('234', '其实，爱情说穿了，普普通通，平平常常，就是男人和女人互相理解，互相尊重，互相关爱，互相取长补短。故事的场景，永远是家庭与社会；故事的情节，永远不外乎一个男人喜欢上了一个女人或一个女人喜欢上了一个男人；故事的结局，不是悲剧就是喜剧，永远没有中间的道路。');
INSERT INTO `weibo` VALUES ('235', '心情不好时，要经常问自己，你有什么而不是没有什么。如果你觉得不爽，你就抬眼望窗外，世界很大，风景很美，机会很多，人生很短，不要蜷缩在一小块阴影里。如果你的生活已处于低谷，那就，大胆走。因为你怎样走都是在向上。');
INSERT INTO `weibo` VALUES ('236', '总以为，那个一路陪着的人不会走，那双一直牵着的手不会松。谁曾想，再见只是一句脱口而出的话语，诀别只是一个随意的转身。有很多人，慢慢地就散了，有很多事，渐渐地就淡了。有些路，只能一个人寂静地走；有些辛酸，只是一个人无奈地尝。人生苦短，但愿有人，给我一世纵容。');
INSERT INTO `weibo` VALUES ('237', '有些人，抓住了就是抓住了，错过了就是错过了，只能说情深缘浅。人生的旅途中有太多的岔口，一转身也许就是一辈子。错过沿途的风景，错过此时的雪季，错过彼时的花季。天涯太远，一生太长，花期荼迷，也抵不住荏苒时光。记忆更迭，谁苍白了谁的等待，谁无悔着谁的执着……');
INSERT INTO `weibo` VALUES ('238', '太真理了：如果你觉得我礼貌，优秀，有修养，你好，我们是泛泛之交；如果你觉得我可爱又幽默，搞笑又谦让，嗨，我们是熟人；如果你觉得我霸道专横，脾气坏又骄傲，恭喜你，我们是很好的朋友；如果你觉得看着我时觉得拿我完全没办法，谢谢你，我爱你……');
INSERT INTO `weibo` VALUES ('239', '你用你的全部生命去谈一次恋爱，那这次恋爱必然不能成功；你用全部精力去谈恋爱，那你一定会被人玩死；你用全部时间去谈恋爱，别人一定会嫌你烦。因为爱情这种事情，你越是勤快，投入越多，它结果就越差。只有像懒人养花一样，爱搭不理，偶尔关心一下，才会新鲜。关心越少，爱的越久。');
INSERT INTO `weibo` VALUES ('240', '当我们说“我爱你”的时候，通常真实的意思是“我需要你”。当我们说“你不再爱我了”，其潜在的意思其实是“你不能再满足我的需要了”。正如弗洛姆所言：真爱是“我需要你因为我爱你”；而假爱是“我爱你因为我需要你”。');
INSERT INTO `weibo` VALUES ('241', 'Will we at last forget ourselves result from the continuous affectation．—— 我们会不会终有一天在不断的假装里，忘记自己……');
INSERT INTO `weibo` VALUES ('242', '电话，打一次没有接，就不要再打第二次；短信，发两次没有回，就不要再发第三次。没有这么卑微的等待，如果你重要，迟早会回过来。保住一份尊严，宁可高傲到发霉，也不要死缠到发疯……');
INSERT INTO `weibo` VALUES ('243', '我就你们几个兄弟。　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　以后少抽点烟，少喝点酒。　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　我还想和你们多玩几年呢。　　　　　　　　　　　　　　　　　　　　　　　　　　　别他妈死我前边了。');
INSERT INTO `weibo` VALUES ('244', '在这世上，总会有人让你愤怒、让你悲伤、让你嫉妒、让你咬牙切齿。并不是他们有多坏，而是因为你很在乎。所以想心安，首先就要“不在乎”。你对事不在乎，它就伤害不到你。你对人不在乎，他就不会令你生气。在乎了，你就已经输了。什么都不在乎的人，才是无敌的……');
INSERT INTO `weibo` VALUES ('245', '佛说，生命中的许多东西是可遇不可求，刻意强求的得不到，而不曾被期待的往往会不期而至。 因此，要拥有一颗安闲自在的心，一切随缘，顺其自然，不怨怒，不躁进，不过度，不强求，不悲观，不刻板，不慌乱，不忘形，不以物喜，不以己悲……');
INSERT INTO `weibo` VALUES ('246', '我们总在期待遇到另一个让自己心动的人，但是却忘了我们常常不自觉的把别人跟曾经爱的人做比较，甚至有时候在别人的身上寻找爱人的影子，只是因为我们拥有曾经的爱情，难舍的不再是一段恋情，而是忘不了的回忆。爱情，把你驻扎在我的心里，不舍忘却。');
INSERT INTO `weibo` VALUES ('247', '特喜欢人家吧？特放不下人家吧？觉得自己特委屈吧？呵呵，结果呢？人家烦了吧？人家嫌你矫情了吧？人家觉得你多余了吧？人家不待见你了吧？人家不理你了吧？你没话找话人家回复不过三字了吧？不要太在乎一个人，越在乎，越卑微。当你特别在乎一个人时，人家就不会在乎你了，你怎么就永远不懂？');
INSERT INTO `weibo` VALUES ('248', '如果你哭，你的对手就会笑；如果你笑，你的对手就会哭。人生就像愤怒的小鸟，每次你失败的时候，总有几只猪在笑。你要做的就是无视嘲笑的声音，给自己打气。自信地微笑，再自信地做好该做的事。勇敢一点，真的没什么大不了！');
INSERT INTO `weibo` VALUES ('249', '我若不坚强，没有人会懂我到底有多痛；我若不坚强，没有人会懂我到底要怎样继续生活下去；我若不坚强，没有人知道我经历了怎么样的生活；我若不坚强，没有人知道我微笑背后所隐藏的伤痛要怎么激励；我若不坚强，没有人知道我在想哭的时候，却发现原来早已没有了眼泪……');
INSERT INTO `weibo` VALUES ('250', '我想要和你白头到老。珍惜爱的每分每秒，等很老很老的时候，依然有你温柔的拥抱和我甜蜜的微笑。即使受了再大的委屈，也坚信你是我这一生的依靠。依然在你的怀里，跟你相对傻傻的笑。不怕以后的日子平淡和简单，只要有你。牵着手，即使你多难过，多生气，也不会松掉，你牵了，就是一辈子续写的美好……');
INSERT INTO `weibo` VALUES ('251', '当你珍惜自己的过去，满意自己的现在，乐观自己的未来时，你就站在了生活的最高处；当你明了成功不会造就你，失败不会击垮你，平淡不会淹没你时，你就站在了生命的最高处……');
INSERT INTO `weibo` VALUES ('252', '不管多么深刻的伤痛，只需7年都会痊愈。因为，有科学家说，7年的时间，可以把我们全身的细胞都更换一遍，一个旧细胞都没有。每一天的坚持都是一种进步。相信总有一天，所有的不爽都会干干净净……');
INSERT INTO `weibo` VALUES ('253', '当明天变成了今天成为了昨天，最后成为记忆里不再重要的某一天，我们突然发现自己在不知不觉中已被时间推着向前走，这不是静止火车里，与相邻列车交错时，仿佛自己在前进的错觉，而是我们真实的在成长，在这件事里成了另一个自己……');
INSERT INTO `weibo` VALUES ('254', '大家有没有发现，那些总说粗话脏话的，往往是心直口快心底很善良的人；真正的文明人是胸怀坦荡、品格高尚的。而那些所谓的文明人，他们往往很伪善，会和你勾心斗角，这种人才是我们真正需要警惕的……');
INSERT INTO `weibo` VALUES ('255', '日久生情，才是真的缘份。喜欢你的人：要你的现在。爱你的人：要你的未来。真正的爱情，不是一见钟情，而是日久生情；真正的缘份，不是上天的安排，而是你的主动；真正的关心，不是你认为好的就要求她改变，而是她的改变你是第一个发现的；真正的矛盾，不是她不理解你，而是你不会宽容她……');
INSERT INTO `weibo` VALUES ('256', '如果一个人充满了快乐、正面的思想，那么好的人、事、物都会和他共鸣，并且被他吸引过来；同样的，如果一个人总是带着悲观的、愤世嫉俗的思想频率，那么，难怪这个人常会有倒霉的事发生在他身上。');
INSERT INTO `weibo` VALUES ('257', 'The rain falls because the sky can no longer handle its weight．Just like the tears fall because the heart can no longer handle the pain．—— 雨水落下来是因为天空无法承受它的重量，眼泪掉下来是因为心再也无法承受那样的伤痛……');
INSERT INTO `weibo` VALUES ('258', '人生如梦，岁月无情。蓦然回首，才发现人活着是一种心情。穷也好，富也好，得也好，失也好。一切都是过眼云烟。想想，不管昨天、今天、明天，能豁然开朗就是美好的一天。不管亲情、友情、爱情，能永远珍惜就是好心情。');
INSERT INTO `weibo` VALUES ('259', 'Can act on impulse, show your passion for life there, always act on impulse, but you do not know how to live.还能冲动，说明你对生活还有激情，总是冲动，说明还你不懂生活。');
INSERT INTO `weibo` VALUES ('260', '找的到的，找不到的，反正我失眠了。回的去的，回不去的，总之我想你了。爱与不爱，我都爱了。等与不等，我都等了。在与不在乎，我都已在乎了。放与不放弃，我都决定不放弃了。你爱或已不爱，自有你心里明白。向前或向后，只有你自己决定。也许结局早已注定。');
INSERT INTO `weibo` VALUES ('261', '曾经，为谁放肆的哭泣，你是吹进我眼里的沙子，模糊了双眼，看不清天空的样子。这一场末路繁华，不倾城，不倾国，却倾我所有。你要的是什么。一生相守。还是一晌贪欢。我要的。只是简单却安稳的生活而已。爱到绝路，覆水难收。最好的幸福，是你给的在乎。');
INSERT INTO `weibo` VALUES ('262', '别等不该等的人，别伤不该伤的心。有些人，注定是生命中的过客；有些事，常常让我们很无奈。与其伤心流泪，不如从容面对。孤独，不一定不快乐；得到，不一定能长久；失去，不一定不再拥有。爱的时候，让他自由；不爱的时候，让爱自由。看的淡一点，伤就会少一点。');
INSERT INTO `weibo` VALUES ('263', '人活一世重要的是经历。苦也好，乐也好，过去的不再重提，追忆过去，只能徒增伤悲，当你掩面叹息的时候，幸福也从你的指缝悄悄的溜走。世上没有不平的事，只有不平的心。不去怨恨，淡然一切，往事如烟。经历了，醉了，醒了，结束了，忘记吧！珍惜现有的生活，幸福就在你身边。');
INSERT INTO `weibo` VALUES ('264', '感情被懂得是一种幸福，期待被懂得是一种孤独。如果失去是苦你怕不怕付出；如果心痛是苦你会不会选择结束；如果追求是苦你要不要执着；如果分离是苦你能向谁倾诉。好多事情到后来才看清楚，心却早已收不回来；好多事情当时丝毫不觉得苦，然而已经找不到来时的路。');
INSERT INTO `weibo` VALUES ('265', 'It has not been the time yet to give up as long as you still feel it is not the end．—— 只要心里还存着不甘心，就还不到放弃的时候。');
INSERT INTO `weibo` VALUES ('266', '人只要生活在这个世界上，就会有很多烦恼。但是，痛苦和快乐取决于你的内心。再重的担子，笑着也是挑，哭着也是挑。再不顺的生活，微笑着撑过去了，就是胜利。多笑一笑，你的人生会更美好，一定让自己微笑如花，只有具备了淡然如花的人生态度，任何困难和不幸才能被锤炼成通向平安的阶梯。');
INSERT INTO `weibo` VALUES ('267', '如果有一天，当你跟爱的人发生争执，你就让他赢，他又能赢到什么？所谓的输，你又输掉了什么？ 这个赢跟输，只是文字上罢了，我们大部分的生命都浪费在语言的纠葛中。其实，争执在很多时候，并没有留下任何输赢，却失去了很多本应珍惜的感情。');
INSERT INTO `weibo` VALUES ('268', 'Love is my sickness and you are my drug，I’m addicted．—— 爱是一种病，我赶上了。你是我的药。我上瘾了。');
INSERT INTO `weibo` VALUES ('269', '有时候我们有些近视，忽略了离我们最真的情感；有时候我们有些远视，模糊了离我们最近的幸福。一辈子很短，永远真的没有多远。所以，对爱你的人好一点，对自己好一点，今天在你枕边，明天可能成了陌路。如果这辈子来不及好好相爱，就更不要指望下辈子还能遇见。');
INSERT INTO `weibo` VALUES ('270', '“Love is when you take away the feeling, the passion, the romance, and you find out you still care for that person.” 　　爱情是：当感觉、热情和浪漫统统拿掉之後，你仍然珍惜对方。');
INSERT INTO `weibo` VALUES ('271', '【男人偷偷“变老”的表现】1、短信只看不发，有事直接拨过去；2、睡觉是越睡越不够；3、喜欢独处；4、爱看法制、探索频道；5、加了很多QQ群，常年闭消息；6、偶尔哼着是几年前的老歌；7、晨勃的硬度大不如从前；8、开始每天吃早餐；9、看见家里不整洁会收拾一下；10、开始叮嘱父母要注意身体。');
INSERT INTO `weibo` VALUES ('272', '当女人不再对你撒娇，她已经对你没热情了；当女人不再深夜催你回家，她已经对你失望了；当女人不再向你解释她的行为和想法，她已经对你厌烦了； 当女人不再与你谈及任何生活、工作的话题，她正在远离你了； 当女人不再与你分享她的快乐，她已经对你漠然了。');
INSERT INTO `weibo` VALUES ('273', 'Different people do the same thing for you，which would make you feel extremely different．Because what you care for is not the thing，but rather for the person who do it．—— 不同的人，为你做同一件事，你会感到天壤之别。因为我们在意的，往往不是人做的事，而只是做事的人……');
INSERT INTO `weibo` VALUES ('274', '有时侯，爱也是种伤害。残忍的人，选择伤害别人；善良的人，选择伤害自己。佛说缘是一块冰，要度五百年。别等不该等的人，别伤不该伤的心。爱的时候，让他自由；不爱的时候，让爱自由。佛说，前世500次回眸，才换来今生的一次擦肩而过。我宁愿用来世和你的一次擦肩而过，来换得今生的500次回眸……');
INSERT INTO `weibo` VALUES ('275', '男孩和女孩吵架了，他们用猜拳的方式决定彼此的对错。输的那方，要向胜的那一方道歉。当女孩伸出剪刀的时候，男孩才缓缓的摊开手掌，那是一个大大的“布”。男孩轻轻说：亲爱的，不管怎样，这场感情里，我都希望你是永远的赢家。女孩眼泪无声的滑落，垂落在男孩温暖的手心里。');
INSERT INTO `weibo` VALUES ('276', '有一种爱，叫做甜蜜；有一种爱，叫做微笑；有一种爱，叫做坦白；有一种爱，叫做依赖；有一种爱，叫做思念；有一种爱，叫做无奈；有一种爱，叫做放弃；有一种爱，叫做伤感；有一种爱，叫做感动；有一种爱，叫做祝福...但，总有一种爱，你我都不知道该叫做什么。');
INSERT INTO `weibo` VALUES ('277', '喜欢你，却不一定爱你。爱你，就一定很喜欢你。其实，喜欢和爱仅一步之遥。但，想要迈这一步就看你。是喜欢迈这一步，还是爱迈这一步。喜欢很容易转变为爱，但爱过之后却很难再说喜欢。喜欢是轻松而淡淡的心态，爱一旦说出了口，就变成了一种誓言，一种承诺。。');
INSERT INTO `weibo` VALUES ('278', '漂泊久了，才知道那不叫自由，自由的前提，是帮心灵寻找归依；跋涉久了，才懂得什么是辛苦，辛苦不仅是忙碌，更是夜深人静后的那份凄凉孤独。有些人，不知何处就散了，我们成了自己灵魂的伴侣；有些事，不知何时就淡了，我们却无法淡漠疼爱自己的情愫。学会对自己好些，多给自己些温暖。');
INSERT INTO `weibo` VALUES ('279', '第一最好不相见，如此便可不相恋。第二最好不相知，如此便可不相思。第三最好不相伴，如此便可不相欠。第四最好不相惜，如此便可不相忆。第五最好不相爱，如此便可不相弃……但曾相见便相知，相见何如不见时。安得与君相诀绝，免教生死作相思。');
INSERT INTO `weibo` VALUES ('280', '\r\n越长大，就越习惯压抑内心的真实感受，不再放声大哭放声大笑，什么都只是淡淡的点到为止。好像越来越没有什么事，可以伤心到落泪，再也找不 出，释放伤感的出口。如果有时间有机会自由的哭，总是好的；如果可以狠狠流出眼泪，就说明心没有干涸。现在明明感觉到痛，却再也无法畅快的流泪。');
INSERT INTO `weibo` VALUES ('281', '有时候，希望时间为自己停下，就这样和喜欢的人地老天荒；有时候，发现身边的人都不了解自己，面对着身边的人，突然觉得说不出话；有时候，在自己脆弱的时候，想一个人躲起来，不愿别人看到自己的伤口；有时候，突然很想逃离现在的生活，想不顾一切收拾自己简单的行李去流浪。');
INSERT INTO `weibo` VALUES ('282', '关于那些青春记忆，太多太多值得回味与心酸。告诫自己不再纠缠那些剪不断理还乱的往事回忆。过去的那些岁月冗杂而伤感，总让人纠结在心。独自眺望远方不断提醒自己，不要在沉沦，应该大步前行，走出尘封记忆的门，也抹掉那些在生命中流淌过的的爱与恨。');
INSERT INTO `weibo` VALUES ('283', '如果你准备接受一份爱，那么，请你一定抬头看看前面的路，想一想自己是否做好了归于平淡、忍受寂寞的准备；如果你想要放弃一段情，那么，请你一定回头看一看来时的路，想一想牵手走过的每一个日子、一起经过的每一次风雨。站在十字路口，你一定要明白自己想要到达的地方，勇敢走出关键的一步。');
INSERT INTO `weibo` VALUES ('284', '相见是幸福，相见是缘分的天定，爱上你就没有回头，你所有的脾气，所有不高兴冲我而来，我都能让你在我的微笑中化解，化为一世的不离不弃，我独霸你心灵的全部。爱的诠释，守候的坚持。');
INSERT INTO `weibo` VALUES ('285', '走得太急时，别忘了停一停，蹲下来聆听路边花开的声音；觉得太累时，短暂地歇一歇，在物我两忘中体味时光的流逝。别想着前面有着更美的风景，当你走到尽头，或许那里只是一片荒芜。别忽略离你最近的那些幸福，有些东西等到失去才知道愧悔。别让行程太寂寞，有一群陪着的人，一双牵着手，比什么都重要。');
INSERT INTO `weibo` VALUES ('286', '有些人离开就是离开了，渐渐地，生活会变得没有什么不同，仿佛那个人不是消失了，而是从未曾出现过。这是我们所希望的，也是必需承认的，原来我们没有那么重要，原来我们并非不可遗忘，面对时间，我们都一样。');
INSERT INTO `weibo` VALUES ('287', '开始，他说，她说。后来，他们一起说。再后来，她说，他不说。最后，她也不说了。——沉默是一个女孩最大的哭声，如果你懂。');
INSERT INTO `weibo` VALUES ('288', '不喜欢就不要选择，喜欢了就要坚持。在一起是一种缘分，不要轻易让喜欢你的人哭泣伤心，好好珍惜在一起的每一分钟，美好的回忆应该留给快乐和欢笑。无论遇到什么事情，都不要轻易说你不喜欢我，不要轻易放弃我这段感情，因为，下一站的人未必比我好！');
INSERT INTO `weibo` VALUES ('289', '『学会控制自己的脾气』看别人不顺眼，是自己修养不够。人愤怒的那一个瞬间，智商是零，过一分钟后才慢慢恢复正常。 人的优雅关键在于控制自己的情绪。用嘴伤害人，是最愚蠢的一种行为。 要学会控制自己的脾气，做一个有修养的人。');
INSERT INTO `weibo` VALUES ('290', '\r\n不要活的太累，不要忙的太疲惫；想吃了不要嫌贵，想穿了不要说浪费；心烦了找朋友聚会，瞌睡了倒头就睡。心态平和永远最美，天天快乐才对。');
INSERT INTO `weibo` VALUES ('291', '明明自己心里有很多话要说，却不知道怎样表达。有时候很低落，觉得自己其实一无所有，仿佛被世界抛弃。明明自己身边有很多朋友，却依然觉得孤单。有时候很想放纵自己，希望自己彻彻底底醉一次，醒来后就能把什么都忘记。明明有着自己的梦想，却是力不从心。有时候握得越紧，失去的也越快。');
INSERT INTO `weibo` VALUES ('292', '有些事，我们明知道是错的，也要去坚持，因为不甘心；有些人，我们明知道是爱的，也要去放弃，因为没结局；有时候，我们明知道无路可走，却还在前行，因为这已成了一种无法改变的习惯。');
INSERT INTO `weibo` VALUES ('293', '有时候，同样的一件事情，我们可以去安慰别人，却说服不了自己。每个人，在困惑苦闷的时候，都需要身边有朋友能够开解一下自己，其实，并非我们不懂得那些道理，只是我们特别需要听到别人把它再复述出来，以来验证和坚定那些道理的真理性。');
INSERT INTO `weibo` VALUES ('294', '心情不好时，要经常问自己，你有什么而不是没有什么。如果你觉得不爽，你就抬眼望窗外，世界很大，风景很美，机会很多，人生很短，不要蜷缩在一小块阴影里。如果你的生活已处于低谷，那就，大胆走，因为你怎样走都是在向上。');
INSERT INTO `weibo` VALUES ('295', '越走越浅的是爱情；越走越急的是岁月，越走越慢的是希望；越走越多的是年龄，越走越少的是时间；越走越长的是远方，越走越短的是人生；越走越远的是梦想，越走越近的是坟墓；越走越深的是亲情，越走越明白的是道路，越走越糊涂的是方向。');
INSERT INTO `weibo` VALUES ('296', '落叶离开树枝，是因为季节的到来；鱼儿离开水，是因为现实的悲哀；你离开我，是因为缘份的尽头。始于此缘，止于此缘，从此，你是你，我只是我。越是短暂的相聚，越是凝聚了一世的真情。多少柔情多少泪，多少梦幻多少醉，一切因相遇太美。分离无罪，幸福无罪，而我们，只剩再见。');
INSERT INTO `weibo` VALUES ('297', '痛过，才知道如何保护自己；哭过，才知道心痛是什么感觉；傻过，才知道适时的坚持与放弃；爱过，才知道自己其实很脆弱。其实，生活并不需要这么些无谓的执著，没有什么就真的不能割舍。');
INSERT INTO `weibo` VALUES ('298', '有些人闯进你的生活，只是为了给你上一课，然后转身离开。不是每个人都适合与你白头到老。有的人，是拿来帮你成长的；有的人，是拿来一起生活的；有的人，是拿来一辈子怀念的。无论生活得多么艰难，最后你总会找到一个让你心甘情愿傻傻相伴的人……');
INSERT INTO `weibo` VALUES ('299', '我喜欢一个人站在窗边望着远处发呆，我喜欢一个人安安静静的不需要安慰，我喜欢一个人毫无目的的走着，我难过时不喜欢说话，一个人哭泣、一个人擦泪、一个人难过、一个人分担。一个人，走陌生的路，看陌生的风景，听陌生的歌。然后在某个不经意的瞬间，才发现，原来，我一直都只是一个人。');
INSERT INTO `weibo` VALUES ('300', '放弃一切东西比人们想像的要容易些，困难在于开始。一旦你放弃了某种你原以为是根本的东西，你就会发现你还可以放弃其他东西，以后又有许多其他东西可以放弃。——卡尔维诺《寒冬夜行人》');
INSERT INTO `weibo` VALUES ('301', '挫折会来，也会过去，热泪会流下，也会收起，没有什么可以让我气馁的，因为，我有着长长的一生，而你，你一定会来。——席慕容《槭树下的家》');
INSERT INTO `weibo` VALUES ('302', '人之间的差别，很少是先天形成的，多是取决后天的努力。要理清学习和挣钱的关系，懂得知识中蕴含的价值，若用体力，你只能生存；若用智慧，你才可能漂亮的生活。不要抱怨上帝对你不公正，总有些人在不如你的情况下，最终走到了你的前面。欲改变现状，先武装脑袋，只有先想到，才能去做到。');
INSERT INTO `weibo` VALUES ('303', '是谁说过，有爱就不会受伤害；是谁说过，有爱就不会分开。我只知道，当我想起这些话的时候会心疼。天知道我多么需要如此爱的温暖，如果可以，我希望在生命终结的那一刻，还可以安心的拥有着。只是，在你冷漠的话语中，我知道这一切都已经埋葬在了所谓的幸福中，彻底的失去了。');
INSERT INTO `weibo` VALUES ('304', '年轻时我们总是在开始时毫无所谓，在结束时痛彻心肺。而长大后成熟的我们避免了幼稚的伤害，却也错过了开始的勇气。——《匆匆那年》');
INSERT INTO `weibo` VALUES ('305', '人只有将寂寞坐断，才可以重拾喧闹；把悲伤过尽，才可以重见欢颜；把苦涩尝遍，就会自然回甘。信了这些，就可以更坦然地面对人生沟壑，走过四季风霜。言者随意，但生命毕竟是一个漫长的过程，每一寸时光都要自己亲历，每一杯雨露都要自己亲尝。——《你若安好便是晴天》');
INSERT INTO `weibo` VALUES ('306', '记忆中的你，一个身影，一个眼神都足以让人心动。害怕这样的思念，却又不得不像河水一样日夜奔流。原以为水再深，河再长再宽，也总有一天会流干。可思念这种感觉并非如此，不论怎样遗忘，却都总会萦绕在脑海中。');
INSERT INTO `weibo` VALUES ('307', '你离开了，永远也不会明白，最难熬的日子我如何熬过；永远也不会明白，最炙热的感情我如何熄灭；永远也不会明白，最苦涩的伤口我如何掩埋；永远也不会明白，最空虚的孤独我如何用血与泪一点点地填满。人山人海总有人先离开，所以我又何德何能，奢求你明白。');
INSERT INTO `weibo` VALUES ('308', '学会放弃，在落泪以前转身离去，留下简单的背影；学会放弃，将昨天埋在心底，留下最美好的回忆；学会放弃，让彼此都能有个更轻松的开始，遍体鳞伤的爱并不一定就刻骨铭心。这一程情深缘浅，走到今天，已经不容易，轻轻地抽出手，说声再见，真的很感谢，这一路上有你。曾说过爱你的，今天，仍是爱你。');
INSERT INTO `weibo` VALUES ('309', '心累了，听听音乐；郁闷了，跳跳舞蹈；伤心了，聊聊心情；失败了，从头再来；生活就该这么过，扫尽阴霾快乐来。虽然有时不如意，一切掌握靠自己，开心面对，做事不觉累。快乐自己，感染所有人。哭就畅快淋漓，雨后必现彩虹。笑就随心所欲，知足才会常乐。');
INSERT INTO `weibo` VALUES ('310', '不爱的时候，心情最为平静，心态最为平稳，性情最为淡泊，与他人最好相处。没有多余的热情，没有多疑的猜忌，没有受伤的敏感，没有变态的恼怒，没有期望的焦虑，没有失望的伤心，没有不着边际的幻想。不爱的时候，才能感觉到彻底的心灵上的自由和解放，原来，不爱才是最好的状态。');
INSERT INTO `weibo` VALUES ('311', '不需要海枯石烂的山盟海誓，只需一生一世的默默相守；不需要多么奢华的烛光晚餐，只需两个人，一桌粗茶淡饭；不需要有座别墅，面朝大海，春暖花开，只需一套小小房子，落地窗，一米阳光；不需要鲜艳，美丽的玫瑰花，只需给我一个宽厚的肩膀。这就是爱，平淡却幸福着；这就是爱，简单并快乐着。');
INSERT INTO `weibo` VALUES ('312', '感情这东西最难的，不在于是不是两个人真的就爱了，难于爱的维持与持久，因为人生并不是只有一天。生活毕竟是现实的，人要经历这样那样的考验，不单单是一句我爱你就解决了。人生中会有很多意想不到的事情，要有足够的耐心去面对。总要经历一些事情，才会明白一些道理，而很多变化就在经历中发生了。');
INSERT INTO `weibo` VALUES ('313', '爱情由纯白到苍白，由苍白到化作尘埃，所有的梦都牵扯得凌乱不堪，什么都不敢去想。把心藏好，把誓言藏好，把碰都不能碰的伤口藏好。放手吧！无奈绝望的承认失败，蜷缩在角落，等待着伤口平复。只有在一个人的夜里，我和我的泪才是安全的.多少个寂静的夜里，自己缩在黑暗中，听着心被撕破的声音流泪。');
INSERT INTO `weibo` VALUES ('314', '当你想找个人说话的时候，才发现有些事情是不能告诉别人的，有些事情是不必告诉别人的，有些事情是根本没有办法告诉别人的，而有些事情即使告诉了别人，你也会马上后悔。那么最好的办法就是静下来，真正能平静自己的只有自己。');
INSERT INTO `weibo` VALUES ('315', '有的人你看了一辈子却忽视了一辈子～～有的人你只看了一眼却影响了你的一生～～有的人热情的为你而快乐却被你冷落～～有的人让你拥有短暂的快乐却得到你思绪的连锁～～有的人一相情愿了N年却被你拒绝了N年～～有的人一个无心的表情却成了永恒的思念～～这就是人生。');
INSERT INTO `weibo` VALUES ('316', '有的人你看了一辈子却忽视了一辈子～～有的人你只看了一眼却影响了你的一生～～有的人热情的为你而快乐却被你冷落～～有的人让你拥有短暂的快乐却得到你思绪的连锁～～有的人一相情愿了N年却被你拒绝了N年～～有的人一个无心的表情却成了永恒的思念～～这就是人生。');
INSERT INTO `weibo` VALUES ('317', '不要认为后面还有更好的，因为现在拥有的就是最好的；不要因为距离太远而放弃，爱情可以和你一起远行；不要因为对方不富裕而放弃，勤劳可以让你们富裕；不要因为父母反对而放弃，你会发现因为这个原因而放弃的爱情，将是你一生的悔恨。其实对于爱情，越单纯越幸福。');
INSERT INTO `weibo` VALUES ('318', '当我们没心没肺地忘记一些人，又花枝招展地遇见一些人，再心如撞鹿地爱上一些人，请不要恍惚，不要怀疑，更无需自责，因为每一次的忘记、遇见与爱恋，都是成长的足迹。所以，不如意时，不要悲伤哭泣，太如意时，不要忘乎所以。爱的时候，请全心全意，不爱的时候，请潇洒离去。');
INSERT INTO `weibo` VALUES ('319', '懂得放弃，在落泪之前转身离去，留下简单的身影；学会放弃，将昨天埋在心底，留下最美好的回忆；学会放弃，让彼此都能有一个更轻松的开始，遍体鳞伤得的爱并不一定刻骨铭心。这一程情深缘浅，走到今天已是不易，轻轻的抽出手，说声再见，真的很感谢这一路有你。');
INSERT INTO `weibo` VALUES ('320', '无论如何选择，只要是自己的选择，就不存在对错后悔。过去的你不会让现在的你满意，现在的你也不会让未来的你满意。当初有胆量去选 同样该有勇气把后果承受。所谓一个人的长大，也便是敢于惨烈地面对自己：在选择前，有一张真诚坚定的脸；在选择后，有一颗绝不改变的心。');
INSERT INTO `weibo` VALUES ('321', '身边的人那么多，懂自己的有几个。不要对我说，我是个好人，我很可爱，我很活泼。我只是个，会自卑，会伤心，会小心眼的普通人。其实，我很好，只是不习惯，只是会偶尔难受一下，只是会在某一瞬间突然很想某个人，只是会在听到某一句熟悉的话时很难过...');
INSERT INTO `weibo` VALUES ('322', '也许等到我忘记了，放弃了，离开了，你才会明白，曾经的相遇，是那么美好。哭累了，沉默了，冷淡了，放弃了。时间一过，却又是想念了。放不下，忘不掉，戒不了，走不开。告诉自己，勇敢离开你。告诉自己，这是最后一次哭泣。多年前的熟悉，多年后的陌生，你还是你，我还是我，只是再也无法回到过去。');
INSERT INTO `weibo` VALUES ('323', '曾经以为没有你，我就没有了全世界，可现在你走了，我的世界还在。原来，失去一个爱的人，它无关于世界；原来，我只是短暂地看不清方向，或者不愿意往前走；原来，你伤害我，只是因为我给了你伤害的机会。——在流泪的时候觉得委屈，其实心里已经慢慢学会坚强。如果我不愿意，没有谁，可以伤害我。');
INSERT INTO `weibo` VALUES ('324', '明白的人懂得放弃，真情的人懂得牺牲，幸福的人懂得超脱。对不爱自己的人，最需要的是理解，放弃和祝福。过多的自作多情是在乞求对方的施舍。爱与被爱，都是让人幸福的事情，不要让这些变成痛苦。既然你们已经经历了，多年以后，偶尔想起，希望都是美好的回忆。');
INSERT INTO `weibo` VALUES ('325', '你的生命中，有没有这么一个人，你无数次说着要放弃，但终究还是舍不得。有没有这么一个人，你心甘情愿地被伤害，即使你知道你会遍体鳞伤。有没有这么一个人，你会在独自一人时想他想到哭泣，却在看见他时故作无所谓地笑。有没有这样一个人，每天可以和TA来去几十条短信，可是一打电话却尴尬无语。');
INSERT INTO `weibo` VALUES ('326', '蝎子在感情上总是专制霸道多疑敏感患得患失，同时却又是忠诚真挚热烈执着倾其所有的。他们太看重感情，无论是爱情还有友情。他们不轻易相信别人，如果有一天他们对你掏心掏肺，他们认定了你，那么从此以后你会在他们心中留有一个独特的位置。');
INSERT INTO `weibo` VALUES ('327', '蝎子一般都充当倾听者，开心和不开心的事都放在心里，只会开解别人，却不会安慰自己。如果蝎子肯为你把心敞开，请珍惜，因为只是为你。');
INSERT INTO `weibo` VALUES ('328', 'Don’t say you love me unless you really mean it, because I might do something crazy like believe it. 不要轻易说你爱我，除非你是认真的，因为我可能会做出一些疯狂的事，比如......相信你');
INSERT INTO `weibo` VALUES ('329', 'You are so lucky, because you can choose to love me or not, but myself only have to choose from loving you or loving you more. 你是幸运的，因为你可以选择爱我或不爱我，而我只能选择爱你还是更爱你。');
INSERT INTO `weibo` VALUES ('330', '天蝎可以对任何一个人好 天蝎可以喜欢好多人 但是当天蝎一旦说爱你 那就是真的爱了 一旦天蝎为了你哭泣那就证明天蝎已经爱你爱到骨子里了 甜言蜜语的话不多 但爱你的事一定会为你做。');
INSERT INTO `weibo` VALUES ('331', '【十二星座最狠、最冷血、分手最绝情指数排行榜】天蝎：冷血指数100。白羊：冷血指数90。金牛：冷血指数80 。狮子：冷血指数70。魔羯：冷血指数60。水瓶：冷血指数50。双子：冷血指数40。处女：冷血指数30。巨蟹：冷血指数20。射手：冷血指数10。双鱼：冷血指数5。天秤：冷血指数0。最近你够狠吗？');
INSERT INTO `weibo` VALUES ('332', '作为高贵孤独的天蝎座，是应该永远高雅的保持高姿态，即使自己伤透了心，也不会去乞求');
INSERT INTO `weibo` VALUES ('333', '天蝎座的人总是喜欢胡思乱想，用一整天的时间去张那些根本就不会存在的问题。搞到自己神经失常，让人担心一整天。');
INSERT INTO `weibo` VALUES ('334', '天蝎座很倔强，有时候明知道自己需要别人的帮助，却因为倔强，死不低头。');
INSERT INTO `weibo` VALUES ('335', '天蝎有时候很执着自己的承诺,就算明知道会撞死南墙也不会回头,一如既往. 不知道这只是我自己的性格所成,还是天蝎有的特性.!');
INSERT INTO `weibo` VALUES ('336', '天蝎爱你的方式，看似不动声色，实则威力极强势。在情意的表达上算不上令人记忆颇深，但点点滴滴的行动上定会让你甜蜜回味。他们爱你，就会习惯性的想要占有你的全部，想要了解你的内心展现与隐藏的世界。不通告一声看你的短信，不商量就替你做决定，也许你会因此恼火，但天蝎别无它意，只是太爱你。');
INSERT INTO `weibo` VALUES ('337', '【12星座最大的缺点】白羊~说话太伤人；金牛~牛脾气不心软；双子~从来不会替你考虑；巨蟹~随时容易伤了心；狮子~太傲气急躁；处女~要求苛刻；天秤~不满不说出悄悄增加冷漠；天蝎~醋意太足过分警惕；射手~做事不和你商量；魔羯~太过刻板；水瓶~有时却暧昧依旧；双鱼~只会想着天上掉馅饼。');
INSERT INTO `weibo` VALUES ('338', '\r\n天蝎是最为爱执着的，同样也是最傲的。尽管痛苦也不要卑微的留守对方身边。花大把的时间跟不同的人玩暧昧，只因为寂寞。那个厮守终生的人迟迟不肯出现。一直等不到，干脆就放纵。但是如果有一天，那个人出现了，必定会去刻骨铭心、撕心裂肺的爱。');
INSERT INTO `weibo` VALUES ('339', '\r\n天蝎 简简单单 不爱解释 就是这么活着 懂的人自然会懂 不懂的 天蝎也不愿意多说 天蝎就是这么活着 喜欢安静 却又怕安静 不管多累 始终会自己走下去。');
INSERT INTO `weibo` VALUES ('340', '天蝎座最大的魅力是他的矛盾所在，没有人知道他们想什么。除了他们自己。他们一时间可以是天使，一时间又可以是恶魔。蝎子愤怒的底线太低，但是真的伤到他了，他会变得跟撒旦一样凶残冷漠。 我总觉得，任何人都是不了解天蝎座的，因为天蝎座是真正的矛盾体。');
INSERT INTO `weibo` VALUES ('341', '【世界上最美的10件事】：1.初吻；2.看日出；3.与很在乎的那个人牵手；4.躺在床上听屋外的雨声；5.每次看到那个人心里七上八下的感觉；6.深夜不眠与室友聊天；7.一个信任的眼神；8.睡觉的时候，太阳照在身上；9.一觉醒来发现还可以睡上几小时；10.冬天里暖和的被窝...');
INSERT INTO `weibo` VALUES ('342', '【心理成熟13个标志】1.不再盲目跟风；2.不再犹豫；3.合理安排时间；4.开始关注新闻国事；5.开始养生；6.在爱情、友情、亲情之间，首先想到亲情；7.不再用哭闹来解决问题；8.重视身边朋友；9.让周围的人快乐；10.得失方面变得大度；11.尊重每个人；12.自信生活；13.淡忘仇恨..');
INSERT INTO `weibo` VALUES ('343', '一位美女去肉菜市场买一公斤猪肉，因为猪肉不够，所以老板从猪脸上割下一小块补进去。 美女见状不答应了，大声地说：“我不要脸！”');
INSERT INTO `weibo` VALUES ('344', '小哥哥带着弟弟一起吃米线。米线分好几种，普通的4元，“过桥米线”则要10元。弟弟不解，问：“哥哥，为什么‘过桥米线’那么贵？”哥哥想了一下，说：“可能这10块钱里包含了过桥费吧！”');
INSERT INTO `weibo` VALUES ('345', '六岁的小婷长得很可爱，常常被班上小男生求婚。有一天，小婷回家后跟妈妈说：“今天小强跟我求婚，要我嫁给他。” 妈妈漫不经心的说：“他有固定的工作吗？” 小婷想了想后说：“他是我们班上付责擦黑板的。”');
INSERT INTO `weibo` VALUES ('346', '每个人都会犯错，你若深爱一个人，无论他如何对你，无论犯什么错，你都会原谅，甚至为他找理由。你若不爱一个人，可能对方只说错一句话，就立刻翻脸分手。所以，当一个人抓住你的小错而分手，不是因为你的错，而是因为不爱你。原谅这种事，只和爱的深浅有关，有多少爱，就有多少原谅。');
INSERT INTO `weibo` VALUES ('347', '【兔斯基语录】1，老鼠嘲笑猫的时候，身旁必有一个洞。2，站在山顶和站在山脚下的两人，虽然地位不同，但在对方眼里，同样的渺小。3，路的尽头，仍然是路，只要你愿意走。4，使我们不快乐的，都是一些芝麻小事，我们可以躲闪一头大象，却躲不开一只苍蝇。');
INSERT INTO `weibo` VALUES ('348', '让爱情稳固的十个好习惯1、鼓励和赞美最重要，2、想要什么你就说 ，3、无伤大雅的癖好可以无视 ，4、亲密不应该流于形式 ，5、每天至少联系一次，6、快乐可以自己创造，7、大胆追求激情，8、爱情也需要检查进度，9、永远彼此尊重，10、没有必要完全透明。');
INSERT INTO `weibo` VALUES ('349', '①爷不是你的小浣熊，玩不出你的其乐无穷。②人生苦短，必须性感。③要么忍，要么残忍。④上联：也许似乎大概是；下联：然而未必不见得。⑤有些事情无须抬杠，表面服从偷偷反抗。⑥勇于认错，坚决不改。⑦男人是条狗，谁有本事谁牵走。⑧誓言只是一时的失言。');
INSERT INTO `weibo` VALUES ('350', '刚才从二楼窗户往下看，操场上有一穿着挺厚衣服的小孩子在地上爬得很快，真的很快。我心里想：跟狗一样的。然后自己骂了自己一句：“呸，怎么说话呢！”然后再看，一女的顺手把他抱起。原来真的是条狗！\r\n');
INSERT INTO `weibo` VALUES ('351', '劳累了，听听音乐；郁闷了，跳跳舞蹈；伤心了，侃侃心情；失败了，从头再来；生活就该这么过，扫尽阴霾快乐来。虽然有时不如意，一切掌握靠自己，开心面对，做事不觉累。快乐自己，感染所有人。哭就畅快淋漓，雨后必现彩虹。笑就随心所欲，知足才会常乐。');
INSERT INTO `weibo` VALUES ('352', '当你爱一个人的时候你就应该说出来。生命只是时间中的一个停顿，一切的意义都只在它发生的那一时刻。不要等。不要在以后讲这个故事。');
INSERT INTO `weibo` VALUES ('353', '人生如車，或长途，或短途；人生如戏，或喜，或悲。很多事，过去了，就注定成为故事；很多人，离开了，就注定成为故人。生命中的故人，积攒的故事，这些都是历练。人就是在历练中慢慢成熟的。一些事，闯进生活，高兴的，痛苦的，时间终将其消磨变淡。经历的多了，心就坚强了，路就踏实了。');
INSERT INTO `weibo` VALUES ('354', '80后的分手信：我爱你，但我又不敢去爱上你，因为我怕失去你，怕将来因为我买不起房子，车子你会离开我，我会比你更加难过，所以我选择疏远你，离开你。而我呢，努力赚钱，买房子，买汽子。中途我会遇到我的另一半，和我一起奋斗的，一起吃苦，一起慢慢品尝我们努力的成果，一起慢慢变老.。');
INSERT INTO `weibo` VALUES ('355', '多少红尘过客，多少过往云烟，一声离别，天涯流散。彩蝶水袖舞清风，暖玉生烟琴几何；梦里销香伊人梦，晓月初升照旧人；秦淮河畔鸳鸯醉，天上宫阙桂花飞。醉眼，泪点伊人颜。心字犹缺，情缘搁浅，一生离散，我却始终落不下那一笔，终是把思念留在那似水年间。');
INSERT INTO `weibo` VALUES ('356', '我们不是很完美的人，但我们要接受不完美的自己。在孤独的时候，给自己安慰；在寂寞的时候，给自己温暖。学会独立，告别依赖，对软弱的自己说再见。生活不是只有温暖，人生的路不会永远平坦，但只要你对自己有信心知道自己的价值，懂的珍惜自己，世界的一切不完美，你都可以坦然面对。');
INSERT INTO `weibo` VALUES ('357', '再执着的未来，也会有以往；再优美的旋律，也会有情殇；再期盼的目光，也会有迷惘；再动人的风花雪月，也等不到地久天长。不要抓住回忆不放，断了线的风筝，只能让它飞，放过它，更是放过自己。要自信甚至是自恋一点，时刻提醒自己我值得拥有最好的一切..');
INSERT INTO `weibo` VALUES ('358', '【为爱情吹风】青年被爱情左右，问智者：我深爱她，但不知道她是否爱我，怎么办？智者：独自去远行，离开一段日子。青年：她身边不乏追求者，我怕失去她。智者：何不给她一个为爱情吹风的机会？青年：要是风吹来了爱情呢？智者：风只会吹灭摇摆不定的烛光，却吹不熄爱情的火苗，爱情之火只会越吹越旺。');
INSERT INTO `weibo` VALUES ('359', '今生，我在人生最美丽的时候遇见你，如果注定是擦肩而过，那么来世，只要你愿意，我愿跪在佛前三百年，求它再安排一次尘缘，携手看花，并肩赏月，即使今生变成一粒细沙，也愿意飘流入你温暖的怀抱。时间能踏碎青春，岁月能改变容颜，但有一种东西却是时间。');
INSERT INTO `weibo` VALUES ('360', '爱是一种说不清道不明的事情。明明说不在乎对方，却总是恋恋不舍的依恋。明明因为对方的谎言伤的很深，却总是无条件的相信对方。明明清楚对方的难过，却总是相互牵绊着。不要在一件别扭的事上纠缠太久。纠缠久了，你会烦，会痛，会累，会神伤，会心碎。');
INSERT INTO `weibo` VALUES ('361', '相爱时一定要珍惜。有时候，这个世界很大很大，大到我们一辈子都没有机会遇见。有时候，这个世界又很小很小，小到一抬头就看见了你的笑脸。所以，在遇见时，请一定要感激；相爱时，请一定要珍惜；转身时，请一定要优雅；挥别时，一定要微笑；因为一转身，一辈子也不会再相见了。');
INSERT INTO `weibo` VALUES ('362', '有人说，生命是初生的无知，少年的纯真，青年的生气，中年的稳健，老年的愤世嫉俗。有人说，生命是母亲的慈祥，父亲的严厉，爱人的柔情，朋友的关心，是一切感情的组合体。有人说，生命是夕阳衬落日，青松立峭壁，万里平沙落秋雁，三月阳春和白雪，是宝刀快马，金貂美酒，是孤月冷歌的漂泊。');
INSERT INTO `weibo` VALUES ('363', '创造的人生也一样是最美的。只有波涛汹涌的浪花，才能显示出大海磅礴的气势;只有一看无际的森林，才能创造出大地的翠绿与娇美;只有勇于跋涉，登上峰顶，才能领略山川的壮丽风光，才能体会创造的欢欣快乐');
INSERT INTO `weibo` VALUES ('364', '人，小时候简单，长大了复杂；穷时简单，富有了复杂；落魄时简单，得势了复杂；君子简单，小人复杂；看自己简单，看别人复杂。世界其实很简单，只是人心很复杂。其实人心也很简单，只是欲望很复杂。 人，一简单就快乐，但快乐的人寥寥无几；人，一复杂就痛苦，可痛苦的人却熙熙攘攘！');
INSERT INTO `weibo` VALUES ('365', '生活就是这样，脚长在自己身上，往前走就对了，直到向往的风景，变成走过的地方。人生本来就是一场即兴演出，直到每段旅程，变成我的舞台。踩着别人的脚印，不如开辟自己的领土，撞到南墙也决不回头，谁说爱好这件事成不了大事，没有做不成的梦，只有不早醒的人。');
INSERT INTO `weibo` VALUES ('366', '假如，爱情可以解释，誓言可以修改。假如，你我的相遇，可以重新安排。那么，生活就会比较容易。假如有一天，我终于能将你忘记。然而，这不是随便传说的故事。也不是明天才要上演的戏剧。我无法找出原稿，然后，将你一笔抹去。');
INSERT INTO `weibo` VALUES ('367', '也许、每个人的背后都有一个美丽的传说；也许、每个人都有他所无法忘记的人；也许、时间会把一切痕迹都给冲淡；也许、在某一年的某一天，那个曾让我们刻骨铭心的身影，突然的就消失了。铭记的太多，淡忘的也太多，于是就有了回忆。');
INSERT INTO `weibo` VALUES ('368', '有的人，总是忘不了，就像有的人，总是记不住；有些话，总是说不出，就像有些话，总是守不牢；有份爱，总是放不下，就像有的爱，总是受不起。---- 你说：何必眷恋？你却不知：某年某月的某一个转身，我答应你，不再爱你，却忘了答应我自己。');
INSERT INTO `weibo` VALUES ('369', '证明你喜欢他(她)的五条证据：一、你经常看他她的空间。 二、你一遍又一遍读他她的短信。 三、你和他她一起走路时，会走得很慢很慢。当你想到他她的时候，你会不经意地流露笑容。 四、你不停地想他她，以至于你没发现这里没有第五条。当你读完这条微博的时候，有个人一直在你的脑海中浮现。');
INSERT INTO `weibo` VALUES ('370', '岁月就象一条河，左岸是无法忘却的回忆，右岸是值得把握的青春年华，中间飞快流淌的，是年轻隐隐的伤感。世间有许多美好的东西，但真正属于自己的却并不多。看庭前花开花落，荣辱不惊，望天上云卷云舒，去留无意。在这个纷绕的世俗世界里，能够学会用一颗平常的心去对待周围的一切，也是一种境界。');
INSERT INTO `weibo` VALUES ('371', '【女人失恋后常做的10件傻事】第一种：暴饮暴食；第二种：借酒浇愁；第三种：借人忘人；第四种：放肆大哭；第五种：疯狂工作；第六种：人前强颜欢笑，人后以泪洗面；第七种：旅行；第八种：休养生息；第九种：复仇 第十种：死性不改，因为相信还有奇迹。');
INSERT INTO `weibo` VALUES ('372', '曾以为自己是世界上最幸福的人，即使失去一切，我还有爱情，以为自己真的找到了懂得爱自己的人，谁知一切都不竟然。我只是活在自己给自己编制的梦里。爱，或许是这个世界上最奢侈的东西，谁都想得到，可是又有几个人能够享有它。还是爱自己吧，唯有自己值得自己狠狠去爱。');
INSERT INTO `weibo` VALUES ('373', '你以为他会陪你天荒地老，总以为自己很幸福，总以固执的姿态去相信。你会敏感会怀疑会害怕，终因他一个眼神而放下所有防备，其实你并没有外表般坚强。你说，一个人也可以过的很好。可你不好，很不好，你会在寂寞中哭泣，会苦笑。那些男人很好，却都不是你的。女人，再坚强，你也只是个需要人疼的女子。');
INSERT INTO `weibo` VALUES ('374', '【幸福生活秘密】8点起床，12点前睡；每天至少翻5页书，跑30分钟步，对1个陌生人微笑，赞美1个人，说1句我爱你；每周至少做1次爱；每月至少有1个进步；每半年旅行1次；每年看1次牙医，做1次体检；至少有1人值得深爱；至少有1个爱好让你契而不舍；至少有1个梦想变成现实；至少有5个电话可在深夜打扰。');
INSERT INTO `weibo` VALUES ('375', '【等你】我，会等你，等你厌倦飘泊的那一天；我，会等你，等你回心转意的那一天；我，会等你，等你愿意和我在一起的那一天；我，会等你，等你离开那个人来到我身边的那一天；我，会等你、等你……然而你可曾知道，世上的爱情，有几份真的经得起等待？');
INSERT INTO `weibo` VALUES ('376', '若再见你，不过是会心一笑，道一句：好久不见……');
INSERT INTO `weibo` VALUES ('377', '【10个爱情心计】1、保持独立；2、不纠缠对方，不会凡事围着他转；3、神秘莫测，不会亮出自己的底牌；4、欲擒故纵，让他心急难堪；5、不让他看见自己的狼狈相；6、以自己的节奏行事；7、保持幽默感；8、相当自信，不会乱吃醋；8、珍爱自己的身体；10、对某些事情的热情超过对他的需要。');
INSERT INTO `weibo` VALUES ('378', '【爱情让我懂得……】1、你以为最酸的感觉是吃醋吗？不是，最酸的感觉是没权吃醋。2、傻与不傻，要看你会不会装傻。3、女人用友情来拒绝爱情，男人用友情来换取爱情。不要见一个爱一个，爱的太多，你的爱就要贬值。男人跟一个女人一起的时间越长，可以容忍她迟到的时间则越短。');
INSERT INTO `weibo` VALUES ('379', '有时候我们感觉走到了尽头，其实只是心走到了尽头。曾以为只要认真地喜欢，就可以打动一个人，原来却只是打动了自己。失去爱的天空，便没有了颜色。直到有一天，你遇到一个人，你们彼此相爱，终于明白，所有的寻觅，再深的绝望，也只是一个过程。几米说过，我总是在最深的绝望里，看见最美的风景。');
INSERT INTO `weibo` VALUES ('380', '有时候我们感觉走到了尽头，其实只是心走到了尽头。曾以为只要认真地喜欢，就可以打动一个人，原来却只是打动了自己。失去爱的天空，便没有了颜色。直到有一天，你遇到一个人，你们彼此相爱，终于明白，所有的寻觅，再深的绝望，也只是一个过程。几米说过，我总是在最深的绝望里，看见最美的风景。');
INSERT INTO `weibo` VALUES ('381', '有些爱，注定有遗憾。有些人，注定会错过。有些情，注定会纠结。人生若只如初见，何事秋风悲画扇。寄一阙相思，诉不尽幽幽情怀。对酒当歌，所谓的天长与无久，徒留遗憾在人间。如不能明白，那么糊涂也是一种幸福。');
INSERT INTO `weibo` VALUES ('382', '乘务员：“先生，飞机马上起飞了，请把手机关掉，好吗？” 乘客：“我开的飞行模式。” 乘务员：“对不起先生，现在山寨手机也很多，我们很难保证每个手机都是符合标准的！” 乘客大怒，“你说啥？你说俺手机山寨的？老子是苹果的！三卡三待呢！不识货别跟老子吵！” ');
INSERT INTO `weibo` VALUES ('383', '有时候，面对着身边的人，突然觉得说不出话。有时候，曾经一直坚持的东西一夜间面目全非。有时候，想放纵自己，希望自己痛痛快快歇斯底里地发一次疯。有时候，别人突然对你说，我觉得你变了，然后自己开始百感交集。有时候，觉得自己拥有着整个世界，一瞬间却又觉得自己其实一无所有..');
INSERT INTO `weibo` VALUES ('384', '淡，是一种至美的境界。人生在世，求淡雅之美。淡名，淡利，无争，无夺，心素如简，人淡如茶。一切自然了，一切脱俗了，一切入了幽远自在的意境了，方为一盏无味而至味的茶。');
INSERT INTO `weibo` VALUES ('385', '在不知不觉中，我突然有一种这样的感觉，不是不爱，是不能爱。走进一个人的世界，哭着，想着，恋着，笑着，讲述着，你总是看着，没有说过一句话。因为有你，所以渴望。但我从那些片只语中听到了失望，于是说服自己习惯独处，习惯一个人默默行走。不是不想爱，是不能爱。因为怕伤人，也怕被伤。.');
INSERT INTO `weibo` VALUES ('386', '是那个人，不说他也懂；不是那个人，说了也没用。是那个人，不解释也没关系；不是那个人，解释也多余。是那个人，不留他也不走；不是那个人，留也留不住。是那个人，不等自然会遇到；不是那个人，原地也会走丢');
INSERT INTO `weibo` VALUES ('387', '一段感情的开始和结束，取决于两人的态度，而和季节是毫不相干的。只是那样的季节的确可以使人的情绪更加沉沦，从而想起很多幸福或是伤感的瞬间，火热的太阳无情的灼烧着大地。风的到来吹开了夏的炎热，消散了些许忧愁，可偏偏夜的来临又似乎是在推波澜，使那种感觉越发强烈');
INSERT INTO `weibo` VALUES ('388', '请不要假装对我好，我很傻，会当真的。爱那么短，遗忘那么长。我还在原地等你，你却已经忘记曾来过这里。原来地久天长，只是误会一场。幸福，就是找一个温暖的人过一辈子。痛过之后就不会觉得痛了，有的只会是一颗冷漠的心。没有什么过不去只是再也回不去....');
INSERT INTO `weibo` VALUES ('389', '人生旅途中，总有人不断地走来，有人不断地离去。当新的名字变成老的名字，当老的名字渐渐模糊，又是一个故事的结束和另一个故事的开始。在不断的相遇和错开中，终于明白：身边的人只能陪着自己走过或近或远的一程，而不能伴自己一生；陪伴一生的是自己的名字和那些或清晰或模糊的名字所带来的感动。');
INSERT INTO `weibo` VALUES ('390', '走在路上，来来往往、匆匆忙忙的行人们面无表情的与我擦肩而过，谁又能明白我内心的悲伤？谁又会为我停下脚步，给我一丝温暖？没有，谁都不会停留。');
INSERT INTO `weibo` VALUES ('391', '有时候 莫名的心情不好，不想和任何人说话，只想一个人静静的发呆；有时候 突然觉得心情烦躁，看什么都觉得不舒服，心里闷的发慌，拼命想寻找一个出口；有时候 感觉自己与世界格格不入，曾经一直坚持的东西一夜间面目全非；有时候 别人突然对你说，我觉得你变了，然后自己开始百感交集…');
INSERT INTO `weibo` VALUES ('392', '曾以为，只要这样爱下去一定能够相守终生，只要两人的心都不变就一定能够天长地久。紧握不放的双手，相信未来一定能携手走到世界尽头。也以为，恋人分手是因为两个人之间有一个爱上了别人，抑或因为厌倦。');
INSERT INTO `weibo` VALUES ('393', '岁月荏苒，不经意间，你我已经走过了两年。在这两年当中不管是快乐还是悲伤，我们都一起欢喜一起忧。网络是你我认识的桥梁，也是让你我不再陌生的地方。相遇之后，在我悲伤时，你会陪我一起难过，在我开心时，你会陪我一起笑，从此，我的世界因你而不再孤单。');
INSERT INTO `weibo` VALUES ('394', '念今生，风烟流年，执手红尘，朝朝暮暮，凝字为爱。两相依，如花眷恋，你是我独守的暖，不相负，繁华唇语缠绵。那日，长空阴晦，如我的心情。踩着碎碎的感伤，两眼含霜，有风吹过，寒依然。闭上眼帘，记不起你完整的笑容，千年红尘，就在这一刻泛起绵绵情愁，我的世界开始下雪。');
INSERT INTO `weibo` VALUES ('395', '如果有一天，你的记忆中没有了我，不要忘记我们相遇的每分每秒。当一个人习惯了另一个人存在的时候，即使没有喜欢和爱，依旧会感到失落，会有点难过。感情的世界里没有公平，我不会去计较。我们在一起的日子，会是我今生最美丽的回忆。');
INSERT INTO `weibo` VALUES ('396', '1、别跟我谈人生，你都不是人生的。2、天天扯蛋，也不嫌蛋疼。3、你真是太监不懂皇帝的累啊。4、你这样的女孩不能嫁人，就算嫁了也是嫁祸于人。5、你复杂的五官，掩饰不了你朴素的智商。');
INSERT INTO `weibo` VALUES ('397', '在不知不觉中，我突然有一种这样的感觉，不是不爱，是不能爱。走进一个人的世界，哭着，想着，恋着，笑着，讲述着，你总是看着，没有说过一句话。因为有你，所以渴望。但我从那些片只语中听到了失望，于是说服自己习惯独处，习惯一个人默默行走。不是不想爱，是不能爱。因为怕伤人，也怕被伤。');
INSERT INTO `weibo` VALUES ('398', '一段感情的开始和结束，取决于两人的态度，而和季节是毫不相干的。只是那样的季节的确可以使人的情绪更加沉沦，从而想起很多幸福或是伤感的瞬间，火热的太阳无情的灼烧着大地。风的到来吹开了夏的炎热，消散了些许忧愁，可偏偏夜的来临又似乎是在推波澜，使那种感觉越发强烈。');
INSERT INTO `weibo` VALUES ('399', '1、前戏都是浮云，高潮才是关键。2、我过的桥比你走的路都多，那是我懒得动；我吃的盐比你吃的饭还多，那是你口味重。3、你就是口井，横竖都是二。4、还没确定是男孩还是女孩，所以还不知道你是要做奶奶还是外婆。');
INSERT INTO `weibo` VALUES ('400', '小时侯，幸福是一件东西，拥有就幸福；长大后，幸福是一个目标，达到就幸福；成熟后，发现幸福原来是一种心态，领悟就幸福。');
INSERT INTO `weibo` VALUES ('401', '喜欢你，不需要理由。不喜欢你，什么都是理由。');
INSERT INTO `weibo` VALUES ('402', '有那么一种爱,明明是深爱,却说不出来. 有一种爱,明明想放弃,却无法放弃. 有一种爱,明知是煎熬,却又躱不开.有一种爱,明知无前路.心却早已收不回来。');
INSERT INTO `weibo` VALUES ('403', '人们最悲哀的，并不是昨天失去得太多，而是沉浸于昨天的悲哀之中。人最愚蠢的，并不是没有发现眼前的陷阱，而是第二次又掉了进去。人最寂寞的，并不是想等的人还没有来，而是这个人已从心里走了出去。');
INSERT INTO `weibo` VALUES ('404', '有些情意，转瞬即逝；有些情意，得以延续，发展成爱情，长路漫漫，最后也许会消逝，但你不会忘记，你曾在一瞬间爱上一个人，那是多么浪漫的一件事。');
INSERT INTO `weibo` VALUES ('405', '有一个人，你一上线就去看她在不在，不在就一阵失落，在，又不敢打扰；有一个人，她的签名只要一换，你立刻就胡思乱想，揣测不安；有一个人，你在线只是在等她，而她的头像却不曾在你的qq里抖动！有一个人，你总是忍不住去看她的空间，即使她什么新鲜事都没有！……有种感情叫做在线对你隐身。');
INSERT INTO `weibo` VALUES ('406', '爱一个女人很容易，而让一个女人心底里踏实和安稳，却于男人是如此的不容易。当一个男人拥有一位爱着自己的女人时，请别轻易的让自己的女人那颗心整天悬在半空而不曾落地般的踏实。');
INSERT INTO `weibo` VALUES ('407', '人生是一种选择，亦是一种放弃。能自由选择的人是幸福的，能适度放弃的心是洒脱的。可惜，有时我们的选择，只有等待，没有结果，只能黯然离开；有时我们的放弃，迫于无奈，含泪转身，走远了依旧频频地回望。所以，有些过去，关于幸福或伤痛，只能深埋心底；有些希冀，关于现在或将来，只能慢慢遗忘。');
INSERT INTO `weibo` VALUES ('408', '两个人最初走在一起，对方为自己做一件很小的事情，我们也会很感动。后来，他要做很多的事情，我们才会感动。再后来，他要付出更多更多，我们才肯感动，人是多么贪婪的动物？珍惜身边的那个人吧!');
INSERT INTO `weibo` VALUES ('409', '逃避不一定躲得过，面对不一定最难受；孤单不一定不快乐，得到不一定能长久；失去不一定不再有，转身不一定最软弱；别急着说别无选择，以为世上只有对于错；许多事情的答案都不是只有一个，所以我们永远有路可以走。');
INSERT INTO `weibo` VALUES ('410', '单身是春天的种子，充满希望；单身是夏天的烈日，热情辉煌；单身是秋天的落叶，自由自在；单身是冬天的雪花，浪漫无限爱情不是索取，而是给予；不是梦想，也不是痴望，爱情不是这样。它是善良，是荣誉，和谐与纯洁的生活.');
INSERT INTO `weibo` VALUES ('411', '一生能有多少爱？什么是缘？什么是命？“发生”是缘；“发生了”是命。什么是前世？什么是来生？记不得的是前世，想不到的是来生。唯一看得见的是今生。当我们说“缘尽”的时候，有没有想过如果从来一遍，那一刻何尝不是缘起？我们都是凡人，一生中谁没有过亏欠？');
INSERT INTO `weibo` VALUES ('412', '有多少感情，明知这份情继续下去没有结果，明知再去坚持，会让自己遍体鳞伤，体无完肤；明知道吃下去的是苦果，却还是要去偿试，不见棺材不流泪，不管是黄连，还是致命的毒药！直到最后痛不欲生，生不如死才肯回头；剩下半条命的时候才肯罢休，才肯放手；甚至乎是身殉情。');
INSERT INTO `weibo` VALUES ('413', '人生就像乘坐一辆公交车：有的人行程长，有的人行程短；有的人很从容，可以欣赏窗外的景色；有的人很幸运，一上车就能落座；有的人不走运，即使全车的人都坐下，他还站着；有时别处的座位不断空出来，唯独身边的这个毫无动静；而当你下定决心走向别处，刚才那个座位的人却正好离开。');
INSERT INTO `weibo` VALUES ('414', '这个世界上有很多好女人和好男人，在漫漫人生路上，我们必定要一直在寻找真正适合自己的人，也许我们要为此付出心酸、眼泪、失落，抑或是铭心刻骨的痛，但这一切都会让自己懂得更多，正因为自己为此付出了很多，我们就更应该坚信，更应该心安理得的忘记，更应该满怀信心的开始。');
INSERT INTO `weibo` VALUES ('415', '忘记一个人，并非不再想起，而是偶尔想起，心中却不再有波澜。真正的忘记，是不需要努力的。');
INSERT INTO `weibo` VALUES ('416', '【他若认可，就嫁给他】你的幸福，我来建筑；你的糊涂，我来弥补；你的任性，我来让步；你的错误，我来修复；你的痛苦，我来承受；你的秘密，我来保守；你的包包，我来看护；你的需求，我来满足；你的美丽，我来守护；你的离开，我会等候；抱你亲你，非我莫属。');
INSERT INTO `weibo` VALUES ('417', '爱情的主体是生活，一起生活你能陪她一时的难过，但你能陪她承受所有的压力吗？你能给她身体的温度，但你能给她生活的方向吗？你可曾想象当热情褪去，拥抱对你已经没有任何吸引力.');
INSERT INTO `weibo` VALUES ('418', '有一句话，我们但愿自己一辈子也不用说：我做错了什么？对方提出分手的时候，我们流着泪问：我做错了什么，你告诉我，我会改的。他带着歉意的说：你没有做错什么，是我的错。你的确没有做错什么，他不爱你，是他的错，与你何干？假如你偏偏要说自己做错，那么，你唯一的过错，便是没有先不爱他。');
INSERT INTO `weibo` VALUES ('419', '正的爱情，要懂得珍惜：没有谁和谁是天生就注定在一起的。一辈子其实不长。能遇心爱的人，是多么幸运的事。为何不紧握着他的手呢。一辈子只爱一个人，并不丢人。 心里明明知道，除了他外还会有更优秀的人出现，可是一个人不能这么贪心的。一颗心需要另一颗心坦诚相待，这样才可以幸福...');
INSERT INTO `weibo` VALUES ('420', '我们这一生注定有很多偶遇，偶遇一件事，偶遇某个人，让我们的生活多了许多曲折。不管怎样，总有那么几件事，让你念念不忘，总有那么一个人，让你陡生叹惜。错过的，就当是路过吧，没有交集的美，仅是心空的幻影，遗忘是彼此最好的怀念。一路走来，偶遇的星光，让我们有遗憾，亦有温暖。');
INSERT INTO `weibo` VALUES ('421', '聪明的人，凡事都往好处想，以欢喜的心想欢喜的事，自然成就欢喜的人生；愚痴的人，凡事都朝坏处想，越想越苦，终成烦恼的人生。世间事都在自己的一念之间。我们的想法可以想出天堂，也可以想出地狱。');
INSERT INTO `weibo` VALUES ('422', '一个人会落泪，是因为痛；一个人之所以痛，是因为在乎；一个人之所以在乎，是因为有感觉；一个人之所以有感觉，仅因为你是一个人！所以，你有感觉，在乎，痛过，落泪了，说明你是完整的一个人。难过的时候，原谅自己，你只不过是一个人而已，没必要把自己看的这么坚不可摧。');
INSERT INTO `weibo` VALUES ('423', '1、俗话说：兔子不吃窝边草；可俗话又说：近水楼台先得月!2、俗话说：宰相肚里能撑船；可俗话又说：有仇不报非君子!3、俗话说：人不犯我，我不犯人；可俗话又说：先下手为强，后下手遭殃!4、俗话说：男子汉大丈夫，宁死不屈；可俗话又说：男子汉大丈夫，能屈能伸。');
INSERT INTO `weibo` VALUES ('424', '要想走进一个女人的心里，光有喜欢和爱是不够的，你必须要懂她：要懂她逞强里的柔弱，给她精神上的支撑；要懂她快乐里的忧伤，给她心灵上的呵护；要懂她的蛮横不讲理，准确回应她眼中的期盼；要懂她心路走向何方，和她风雨中一起走，她的要求其实也不多，她只是想找一个完全懂他的爱人');
INSERT INTO `weibo` VALUES ('425', '世间最悲哀的事，莫过于两个人彼此倾心，却因为沉默而错过。幸福不是等来的，爱一个人就要大胆去表白，只要你努力争取过，以后就不会后悔；如果因为你的沉默，而错过了一份美好的爱情，你就可能会一生耿耿于怀。心里有爱就要大声说出来，只有你勇敢地表达自己的爱，爱情才不会有遗憾。');
INSERT INTO `weibo` VALUES ('426', '一个人最幸福的时刻，就是找对了人，他纵容你的习惯，并爱着你的一切。');
INSERT INTO `weibo` VALUES ('427', '幸福不是房子有多大，而是房里的笑声有多甜；幸福不是你能开多豪华的车，而是你开着车能平安到家；幸福不是爱人多漂亮，而是爱人的笑容多灿烂；幸福不是在成功时喝彩多热烈，而是失意时会不会有个声音对你说——朋友别倒下；幸福不是听过多少甜言蜜语，而是在你伤心时能有人对你说：有我在。');
INSERT INTO `weibo` VALUES ('428', '爱，是一种责任，我不是碰不到更好的，而是因为有了你，我不想再碰更好的。 我不是不会对别人动心，而是因为已经有了你，我就觉得没必要再对其他人动心。 我不是不会爱上别的人，而是我更加懂得珍惜你，能在一起不容易，即使你不是最好的，甚至不是最适合我的，但却是我最珍惜的');
INSERT INTO `weibo` VALUES ('429', '男人的魅力，在于一种风度气韵，而与容貌无关的。男人的魅力，在于一种诚实守信，而与权钱无关的。男人的魅力，在于宜动宜静之间，理性与感情交织。男人的魅力，在于人生阅历积淀，气已定神也闲了。男人魅力的最高境界，应该是人性、人格、人生、思想、才气、胸怀、气质、真善美的灵光荡漾。');
INSERT INTO `weibo` VALUES ('430', '【一辈子至少要去一次的八个中国小镇】1、最美的地方——乌镇。2、人间天堂——丽江古城。3、现代桃花源——水墨婺源。4、风雨边城——凤凰古城。5、人间天上——九寨沟。6、最完整的古县城——平遥。7艺术之都——敦煌。8西部第一村——新疆布尔津白哈巴村。');
INSERT INTO `weibo` VALUES ('431', '世界上最远的距离，不是爱，不是恨，而是熟悉的人，渐渐变得陌生。虽然最好的时光，总是特别短，但曾有过的感动，我们都会记得。');
INSERT INTO `weibo` VALUES ('432', '每个人的心里都潜藏着一条悲伤的河流。 你有你的疼痛，我有我的艰辛，并非不懂，只是无暇顾及。 如人饮水，冷暖自知。想要温存永生，只需嘴角上扬，那就是最美好的故事。');
INSERT INTO `weibo` VALUES ('433', '在对的时间，遇见对的人，是一生幸福；在对的时间，遇见错的人，是一场心伤；在错的时间，遇见错的人，是一段荒唐；在错的时间，遇见对的人，是一阵叹息。你最爱的，往往没有选择你；最爱你的，往往不是你最爱的；而最长久的，偏偏不是你最爱也不是最爱你的，只是在最适合的时间出现的那个人。');
INSERT INTO `weibo` VALUES ('434', '我们都是尘世凡间的普通人，与其仰望天际漂泊的云彩，不如做一枝倾情绽放的花朵，用简单快乐之心，淡视风云变幻，笑迎雪雨冰霜；不避生活常态，不畏他人嘲讽；盛开时无须肆意遮掩，凋零时坦然面对凄凉；散发着自己的芬芳，坚守着自己的故事；用装扮世界来体现内涵，用愉悦众生来诠释美丽。');
INSERT INTO `weibo` VALUES ('435', '在以前的痛苦是因为记不起，今天的痛苦是怕自己无法忘记。如果你开心和悲伤时，想到的都是同一个人，那就最完美了。然而开心时，有太多人可以和你分享；悲伤时，却多是独自度过。如果日子过得快乐，自己一人也很好；悲伤，却不是很多人可以和你分担。你愿意把悲伤告诉他，他才是你最想亲近和珍惜的人。');
INSERT INTO `weibo` VALUES ('436', '我一直认为最后的最后，离开的会是你，因为你不爱我，因为你不在乎，可是，最后还是我离开了你。这样的爱真的很累，我很明白我要的是什么，我并非因为寂寞而恋爱。');
INSERT INTO `weibo` VALUES ('437', '欲相守，难相望，人各天涯愁断肠。爱易逝，恨亦长，灯火阑珊人彷徨。春花开，秋叶落，繁华过后留残香。望长空，叹明月，形单影只心惆怅。酒意浓，心亦醉，罗衫轻袖舞飞扬。思秋水，念伊人，咫尺天涯媲鸳鸯。前世情，今生债，红尘轮回梦一场。');
INSERT INTO `weibo` VALUES ('438', '【男女心理互动】一个温顺女人变得泼辣，一定是男人不争气，她不得不出头。一个纯洁、清高女人变得恶俗，一定是男人档次不够高。相反，一个平庸女人，相貌变得可爱，眼睛变得灵光，举手投足变得有风度，一定有一个好男人。男人要知道，女人的美有你一半的功劳，她的丑也有你一半的过错。');
INSERT INTO `weibo` VALUES ('439', '忘记无缘的朋友，忘记投入却不能收获的感情，忘记花开花落的烦恼，忘记夕阳易逝的叹息，忘记一切不愿记忆的东西。对万事万物不要刻意的追求，否则很难走出患得患失的误区。生命要升华出安静超然的精神，懂得放弃，学会忘记，也就收获了幸福。');
INSERT INTO `weibo` VALUES ('440', '杯子寂寞，倒进开水，滚烫的感觉，就是恋爱的感觉。水变温了，杯子很舒服，这是生活的感觉。水变凉了，杯子害怕，也许这就是失去的感觉。水彻底的凉，杯子难受，把水倒出。杯子很舒服，杯子也掉在地上摔成一片一片的。发现每一片上都有水的痕迹,它知道心里还爱着水,想再爱一次水,却不可能了！');
INSERT INTO `weibo` VALUES ('441', '如果相爱真的可以相守百年，可为何经不起红尘韶光里流年的等待，曾经，是谁许我一世欢颜，又是谁曾许我来生相守的誓约，那么的坚定，那么的决绝！');
INSERT INTO `weibo` VALUES ('442', '很多事情，我并不是不知道，不在意，只是不想仅仅计较，不想戳穿你。那么请你在骗我的同时，也请注意点分寸。');
INSERT INTO `weibo` VALUES ('443', '人生旅途中，总有人不断地走来，有人不断地离去。当新的名字变成老的名字，当老的名字渐渐模糊，又是一个故事的结束和另一个故事的开始。在不断的相遇和错开中，终于明白：身边的人只能陪着自己走过或近或远的一程，而不能伴自己一生；陪伴一生的是自己的名字和那些或清晰或模糊的名字所带来的感动。');
INSERT INTO `weibo` VALUES ('444', '【男人深爱女人的九种表现】1.在你难过时，他会不安；2.你高兴时，他很高兴；3.他常给你买东西，却舍不得给自己买；4.他一般会顺你的意；5.他很照顾你的家人；6.他有时也生气,但不吵架，过后会及时交流；7.他很注重你的感受；8.他在亲朋好友面前总夸奖你；9.他为人坦诚，对你几乎不会撒谎。.');
